### ISSUE TITLE
Okta auth quickstart section links do not work

### ISSUE THREAD

**Issue by michaeltamaki-okta** [okta/okta-developer-docs#1001]
## Steps to reproduce

- Go to the Okta Auth Quickstart page: https://developer.okta.com/quickstart/#/okta-sign-in-page/nodejs/express
- Hover over any section, such as "Create an Okta Account"
- Click the copy link icon
- Paste the link into a new tab
- The URL changes to https://developer.okta.com/quickstart/#/okta-sign-in-page/nodejs/express and does not scroll to section.

![dev-docs-link](https://user-images.githubusercontent.com/39275539/75184515-5cae6580-56f9-11ea-83f8-45ed4c3cdf66.gif)

**Comment by alexdahl-okta** [comment]
I don't believe the anchor link was intended to modify the user's clipboard. It modifies the page path in the address bar, allowing the user to decide what they want to do next – bookmark it, drag it to another app, or copy it manually.

But it's a good question – should the button we provide copy the URL to clipboard? Whether yes or no, is the interaction design sufficiently clear about the outcome?

This would apply generally across the site, not just to quickstarts.

**Comment by dogeared** [comment]
moved to: https://oktainc.atlassian.net/browse/OKTA-360235
