### ISSUE TITLE
[Prose]: Early Access flag is causing guide text to right indent

### ISSUE THREAD

**Issue by susanharper-okta** [okta/okta-developer-docs#1011]
When a guide has the Early Access flag (<ApiLifecycle access="ea" />)at the top of the page, the rest of the content right indents on that page. On the rest of the pages (without an Early Access flag), the content is not right-indented. Confirmed behavior in Chrome and Firefox.

Example pages: https://developer.okta.com/docs/guides/request-user-consent/overview/
https://developer.okta.com/docs/guides/implement-oauth-for-okta/overview/

<img width="1098" alt="Screen Shot 2020-02-27 at 10 18 20 AM" src="https://user-images.githubusercontent.com/45509385/75469186-cc1b9380-594b-11ea-9f8d-6f2a2b106788.png">
<img width="1016" alt="Screen Shot 2020-02-27 at 10 18 08 AM" src="https://user-images.githubusercontent.com/45509385/75469192-ce7ded80-594b-11ea-928a-fd6034dbbb58.png">

**Comment by dogeared** [comment]
Moed to: https://oktainc.atlassian.net/browse/OKTA-365100
