### ISSUE TITLE
[Prose]: Early Access flag in a Note causes formatting issues

### ISSUE THREAD

**Issue by susanharper-okta** [okta/okta-developer-docs#1012]
The Early Access flag (<ApiLifecycle access="ea" />) placed inline in a >Note tag causes formatting issues with the text - adds an underscore directly after the image and then the formatting between text lines is deep. Verified behavior in Chrome and Firefox.

Example page: https://developer.okta.com/docs/reference/api/oauth-clients/#response-parameters

<img width="885" alt="Screen Shot 2020-02-27 at 10 29 59 AM" src="https://user-images.githubusercontent.com/45509385/75469545-70053f00-594c-11ea-80d4-603e278ba249.png">

**Comment by dogeared** [comment]
Moved to: https://oktainc.atlassian.net/browse/OKTA-365101
