### ISSUE TITLE
React documentation: "AuthSdkError: No issuer passed to constructor"

### ISSUE THREAD

**Issue by sriks316** [okta/okta-developer-docs#1077]
There is an error that shows with this doc:
https://developer.okta.com/code/react/okta_react/
When run the app and authenticate you get this:
"AuthSdkError: No issuer passed to constructor"

Below is something that I tried that got it working. Please advise.

On line 16 of LoginForm.js
   Replace:
	this.oktaAuth = new OktaAuth({ url: props.baseUrl });
   With:
	this.oktaAuth = new OktaAuth({ issuer: ‘yourbaseurl’ }); // change ‘url’ to ‘issuer’ and also I had to hard code the base url(props.baseUrl doesn’t work)

**Comment by dogeared** [comment]
Sorry for late response @sriks316.

Would @jakubvul please have someone look to see if this is still an issue?

**Comment by brianduffield-okta** [comment]
Closing as no longer applicable / fixed

The link from the issue goes to the new OIE version of this guide, which does not have the code issue: https://developer.okta.com/docs/guides/sign-in-to-spa-authjs/react/main/

The classic archived version of this doc, https://developer.okta.com/docs/guides/archive-sign-in-to-spa-authjs/react/main/ , also has this code snippet updated.
