### ISSUE TITLE
Compiling Client Build Notice

### ISSUE THREAD

**Issue by bretterer** [okta/okta-developer-docs#113]
```
[4:09:33 PM] Compiling Client

With `useBuiltIns` option, required direct setting of `corejs` option

```

This happens during `yarn dev`

**Comment by dogeared** [comment]
@bretterer - is this still an issue?

**Comment by dogeared** [comment]
https://oktainc.atlassian.net/browse/OKTA-351204?atlOrigin=eyJpIjoiZTlmMGI2YTZmNmMxNDBkN2JjMmVmN2Q2ODc4OTI1MjEiLCJwIjoiaiJ9

**Comment by bretterer** [comment]
Not sure... Suggest running `yarn dev` and see if the output contains that?

**Comment by dogeared** [comment]
@albertchen-okta this can be closed

**Comment by dogeared** [comment]
@bretterer - just to be clear, it's not going away - we're just tracking it in Jira

**Comment by albertchen-okta** [comment]
Closing, thanks
