### ISSUE TITLE
Title component in prose layout have offset when icon property is defined in front matter with missing icon url.

### ISSUE THREAD

**Issue by mrunalpatel-okta** [okta/okta-developer-docs#1131]
![image](https://user-images.githubusercontent.com/59921357/80127338-2c047400-8562-11ea-830a-3e76ad6c5b80.png)

---
title: Understanding SAML
layout: docs_page
icon: /assets/img/icons/saml.svg
meta:
  - name: description
    content: Secure Authentication Markup Language is a standards-based protocol for exchanging digital authentication signatures. Learn how SAML operates and how to set up SAML applications in Okta.
---

note that saml icon doesn't exist.

**Comment by alexdahl-okta** [comment]
Appears to be resolved, but let me know if I'm mistaken.
