### ISSUE TITLE
List users with filter missing case sensitivity information

### ISSUE THREAD

**Issue by osman-kara** [okta/okta-developer-docs#1179]
Filter values are case sensitive unlike search values and there is no mention about the case sensitivity in filter section. It would be nice to have that mention in docs. 

Suggested wording "Property names and string values in the filter parameter are case sensitive whereas operators (eq, sw, etc.) are case insensitive."

**Comment by jakubvul-okta** [comment]
This is documented here: https://developer.okta.com/docs/reference/api-overview/#filtering
