### ISSUE TITLE
SAML FAQs page is missing from tree nav

### ISSUE THREAD

**Issue by alexdahl-okta** [okta/okta-developer-docs#1213]
https://developer.okta.com/docs/concepts/saml/faqs/ does not appear in the tree nav.

All articles should appear in the tree nav, in the appropriate hierarchy.

`Understanding SAML` should be a sub-section, like `Sign in Your Users` in Reference.
It should have two children:

- The SAML overview article, with a meaningful title (currently at https://developer.okta.com/docs/concepts/saml/ )
- The SAML technical questions article (currently https://developer.okta.com/docs/concepts/saml/faqs/)

**Comment by albertchen-okta** [comment]
tracking in https://oktainc.atlassian.net/browse/OKTA-320796
