### ISSUE TITLE
Top nav responsiveness

### ISSUE THREAD

**Issue by alexdahl-okta** [okta/okta-developer-docs#1215]
When the viewport is between approximately 770–970px, the top nav is cut off and not all content is accessible:
<img width="782" alt="Screen Shot 2020-05-28 at 3 04 03 PM" src="https://user-images.githubusercontent.com/26014482/83209823-f4569200-a0f4-11ea-90a5-fe95c75bf9e4.png">

A medium breakpoint response is likely required.

**Comment by dogeared** [comment]
Moved to: https://oktainc.atlassian.net/browse/OKTA-365115
