### ISSUE TITLE
Add description on CSR

### ISSUE THREAD

**Issue by arvindkrishnakumar-okta** [okta/okta-developer-docs#1218]
**Ref:** https://developer.okta.com/docs/reference/api/apps/

The doc should probably be updated, but as a developer just `CSR` could mean multiple things

_Originally posted by @bdemers in https://github.com/okta/okta-sdk-java/pull/384_

https://oktainc.atlassian.net/browse/OKTA-302089

**Comment by dogeared** [comment]
Closing as: https://oktainc.atlassian.net/browse/OKTA-302089 is marked resolved.
