### ISSUE TITLE
If you navigate directly to a documentation link, the link address changes to something else in the browser address bar.

### ISSUE THREAD

**Issue by dogeared** [okta/okta-developer-docs#122]
Steps to reproduce:

Browse to: https://developer.okta.com/docs/api/resources/apps/#add-bookmark-application

After the page fully resolves, you'll notice that the url changes in the browser address bar to:

https://developer.okta.com/docs/api/resources/apps/#add-application

**Comment by bretterer** [comment]
Appears to be working now.
