### ISSUE TITLE
Stack selector icons for IdPs

### ISSUE THREAD

**Issue by alexdahl-okta** [okta/okta-developer-docs#1246]
After the first page, the https://developer.okta.com/docs/guides/add-an-external-idp/ guide has a stack selector containing identity providers.

Currently, only OIDC and SAML show icons.

<img width="671" alt="idps" src="https://user-images.githubusercontent.com/26014482/84696955-0142f600-aee9-11ea-9494-f291ea7c2d1d.png">

All providers should have icons, matching the icons in the Admin Console for providers that appear there.

**Comment by dogeared** [comment]
Moved to: https://oktainc.atlassian.net/browse/OKTA-365136
