### ISSUE TITLE
SMS template type

### ISSUE THREAD

**Issue by gabrielsroka** [okta/okta-developer-docs#1303]
on https://developer.okta.com/docs/reference/api/templates/#sms-template-types

it mentions only `SMS_VERIFY_CODE`

but https://developer.okta.com/docs/reference/api/templates/#request-example-4 also mentions `SMS_ENROLLMENT_CODE`

and they both right?

also, it says "The key portion is a two-letter country code" but in Okta, it shows, eg, `nl_NL` which has both a country code and language code. should this be more fully explained?

**Comment by dogeared** [comment]
Moved to: https://oktainc.atlassian.net/browse/OKTA-365142
