### ISSUE TITLE
Make authentication w/ our Postman collections more visible/discoverable.

### ISSUE THREAD

**Issue by quyle-okta** [okta/okta-developer-docs#1305]
I just imported an Okta Postman Collection from this page:
https://developer.okta.com/docs/reference/postman-collections/

As a new Okta developer, it wasn't clear to me how to authenticate Okta API calls.  This sentence is buried at the bottom of the Postman list:

> Learn more about how to get started with the Okta REST APIs.

We should move this sentence at the top of the Postman collections page as well as this one:

> These buttons are also available at the top of each API reference page.

**Comment by dogeared** [comment]
moved to: https://oktainc.atlassian.net/browse/OKTA-366428
