### ISSUE TITLE
"Basic auth digest"

### ISSUE THREAD

**Issue by mwangersjo** [okta/okta-developer-docs#1350]
Hi! I'm going through the guide on setting up a Python App ([this guide](https://github.com/okta/samples-python-flask/tree/master/okta-hosted-login) and the https://developer.okta.com/docs/guides/implement-auth-code/overview/ guide) and had a comment about a doc page. 

Very nitpicky, I'm not sure how relevant/correct it is. Feel free to close if it's does not make sense. It's regarding the wording on a comment about Basic Auth in [this file](https://github.com/okta/okta-developer-docs/blob/f23a76d1a2a615ce9153796a70abc54118bf9d06/packages/%40okta/vuepress-site/docs/guides/implement-auth-code/exchange-code-token/index.md).

There is a mention of "Basic Auth Digest". Not sure if 'digest' is the right word for the Base64 encoded data, I think it's used mainly for output from a hash function? The difference between Basic Access and Digest Access is just that hashing.

**Comment by dogeared** [comment]
Internal tracking: https://oktainc.atlassian.net/browse/OKTA-366437

**Comment by brianduffield-okta** [comment]
Thanks. This update has been made, and the internal ticket closed.
