### ISSUE TITLE
Typo in Golang Docs Homepage

### ISSUE THREAD

**Issue by rdegges** [okta/okta-developer-docs#1383]
![Screenshot from 2020-08-27 14-51-26](https://user-images.githubusercontent.com/90247/91498564-d247e980-e874-11ea-94bb-72ff50b18d07.png)

The Go home page incorrectly has a subsection titled "Java Libraries" which doesn't make any sense. To keep parity with the other language landing pages, I believe this section should be titled "Okta JWT Verifier for Go"

**Comment by dogeared** [comment]
moved to: https://oktainc.atlassian.net/browse/OKTA-366439
