### ISSUE TITLE
Missing link to Okta JS Management SDK on JS homepage

### ISSUE THREAD

**Issue by rdegges** [okta/okta-developer-docs#1385]
![Screenshot from 2020-08-27 15-15-08](https://user-images.githubusercontent.com/90247/91500304-1b4d6d00-e878-11ea-8df7-24c50eb6667f.png)

As you can see, this page is missing a link to our [JavaScript management SDK](https://github.com/okta/okta-sdk-nodejs).

**Comment by dogeared** [comment]
moved to: https://oktainc.atlassian.net/browse/OKTA-366440
