### ISSUE TITLE
Missing link to our Okta React library on the JS homepage

### ISSUE THREAD

**Issue by rdegges** [okta/okta-developer-docs#1387]
![Screenshot from 2020-08-27 15-15-08](https://user-images.githubusercontent.com/90247/91500447-66678000-e878-11ea-91b1-793aace46353.png)

We are missing a link to our [react library](https://github.com/okta/okta-oidc-js/tree/master/packages/okta-react) on this page.

**Comment by dogeared** [comment]
moved to: https://oktainc.atlassian.net/browse/OKTA-366443
