### ISSUE TITLE
Missing link to our Angular library on the JS docs homepage

### ISSUE THREAD

**Issue by rdegges** [okta/okta-developer-docs#1389]
![Screenshot from 2020-08-27 15-15-08](https://user-images.githubusercontent.com/90247/91500545-96168800-e878-11ea-86c9-4fe663c061fe.png)

We are missing a link to our [Angular library](https://github.com/okta/okta-oidc-js/tree/master/packages/okta-angular) on this page.

**Comment by dogeared** [comment]
moved to: https://oktainc.atlassian.net/browse/OKTA-366455
