### ISSUE TITLE
Broken link to our Vue.js SDK on our Vue.js docs homepage

### ISSUE THREAD

**Issue by rdegges** [okta/okta-developer-docs#1390]
![Screenshot from 2020-08-27 15-21-44](https://user-images.githubusercontent.com/90247/91500827-1a690b00-e879-11ea-8532-8383f468cecb.png)

This link is a 404 on our docs page. It currently links to: https://github.com/okta/okta-oidc-js/tree/master/packages/okta-vue (404)

**Comment by mraible** [comment]
Fixed! Now it links to https://github.com/okta/okta-vue. I'd close this issue, but I don't have permission. 😔
