### ISSUE TITLE
Python docs landing page is missing copy

### ISSUE THREAD

**Issue by rdegges** [okta/okta-developer-docs#1391]
Here's what the Python landing page looks like today:

![Screenshot from 2020-08-27 15-25-48](https://user-images.githubusercontent.com/90247/91501036-98c5ad00-e879-11ea-91c9-07626a982d51.png)

Here's the Node landing page, for comparison. Notice the missing copy?

![Screenshot from 2020-08-27 15-26-05](https://user-images.githubusercontent.com/90247/91501082-b85cd580-e879-11ea-92fc-65b89ef43893.png)

It feels weird to have a landing page for Python that doesn't have any wording, just a create account button =0

**Comment by noinarisak** [comment]
Looks like with the new design it was resolved @rdegges.

**Comment by dogeared** [comment]
moved to: https://oktainc.atlassian.net/browse/OKTA-366456
