### ISSUE TITLE
Update awkward wording on all programming language landing pages

### ISSUE THREAD

**Issue by rdegges** [okta/okta-developer-docs#1392]
Right now, all of our programming language landing pages:

- https://developer.okta.com/code/java/
- https://developer.okta.com/code/nodejs/
- etc...

Have the same header. It looks like this:

![Screenshot from 2020-08-27 15-28-28](https://user-images.githubusercontent.com/90247/91501194-f78b2680-e879-11ea-9946-a9fe7b2cc454.png)

This one (Java) reads "Add User Authentication and Okta Resource Management to Your Java App". That phrasing sounds sort of awkward, because the phrase "Okta Resource Management" is unclear/vague/not how most people would reference our API.

What if we instead standardize the phrasing to read "Add User Management to Your <language> Apps"? I feel like that's a bit simpler, easier to understand, and also much shorter so the titles won't wrap as much.

**Comment by dogeared** [comment]
moved to: https://oktainc.atlassian.net/browse/OKTA-366457
