### ISSUE TITLE
Missing link to REST API reference on REST API homepage

### ISSUE THREAD

**Issue by rdegges** [okta/okta-developer-docs#1398]
The REST API homepage on our docs site, https://developer.okta.com/code/rest/, doesn't appear to link to our [REST API reference](https://developer.okta.com/docs/reference/) material. It feels odd to have it not link to this, since this the one place on the website I would expect to find it.

**Comment by dogeared** [comment]
moved to: https://oktainc.atlassian.net/browse/OKTA-368560
