### ISSUE TITLE
Sample code throws exception when not logged in

### ISSUE THREAD

**Issue by reverentgeek** [okta/okta-developer-docs#1404]
The Node.js + Express sample code for [getting user info](https://developer.okta.com/docs/guides/sign-into-web-app/nodeexpress/get-user-info/) throws an exception if the user is not logged in. The sample code should be changed to:

```js
app.get('/', (req, res) => {
  if (req.userContext && req.userContext.userinfo) {
    res.send(`Hi ${req.userContext.userinfo.name}!`);
  } else {
    res.send('Please Sign In');
  }
});
```

**Comment by dogeared** [comment]
moved to: https://oktainc.atlassian.net/browse/OKTA-368653
