### ISSUE TITLE
Sample code for configuring Express OIDC middleware uses deprecated syntax causing runtime exception

### ISSUE THREAD

**Issue by reverentgeek** [okta/okta-developer-docs#1405]
The [configure packages](https://developer.okta.com/docs/guides/sign-into-web-app/nodeexpress/configure-packages/) sample code uses `redirect_uri` which has been deprecated in favor of `appBaseUrl`. Using this sample code with the latest OIDC middleware will result in a runtime exception.

**Comment by dogeared** [comment]
moved to: https://oktainc.atlassian.net/browse/OKTA-368654
