### ISSUE TITLE
Recommend changing sample code to use environment variables

### ISSUE THREAD

**Issue by reverentgeek** [okta/okta-developer-docs#1406]
Currently, the placeholders for configuration values used in ["Add and configure packages"](https://developer.okta.com/docs/guides/sign-into-web-app/nodeexpress/configure-packages/) is confusing. It is most common to use environment variables in Node.js applications. I suggest updating the following.

Change

> You can configure the properties of your application with configuration files, environment variables, or other framework specific techniques.

to

> You can configure the properties of your application with configuration files, environment variables, or other framework-specific techniques. The following example uses environment variables.

Change the sample code to the following:

```js
const session = require('express-session');
const { ExpressOIDC } = require('@okta/oidc-middleware');

// session support is required to use ExpressOIDC
app.use(session({
  secret: process.env.SESSION_SECRET,
  resave: true,
  saveUninitialized: false
}));

const oidc = new ExpressOIDC({
  issuer: `https://${ process.env.OKTA_ORG_URL }/oauth2/default`,
  client_id: process.env.OKTA_CLIENT_ID,
  client_secret: process.env.OKTA_CLIENT_SECRET,
  appBaseUrl: process.env.APP_BASE_URL,
  scope: 'openid profile'
});

// ExpressOIDC attaches handlers for the /login and /authorization-code/callback routes
app.use(oidc.router);
```

**Comment by dogeared** [comment]
moved to: https://oktainc.atlassian.net/browse/OKTA-368656
