### ISSUE TITLE
Add a markdown linter to travis to check common errors

### ISSUE THREAD

**Issue by bretterer** [okta/okta-developer-docs#141]
Lots of table errors have popped up along with some others items here and there.  We should look at adding some form of a markdown linter to our tool set for travis ci

**Comment by dogeared** [comment]
Is this something you did already or still needs to be done @bretterer?

**Comment by bretterer** [comment]
Still needs to be done

**Comment by dogeared** [comment]
https://oktainc.atlassian.net/browse/OKTA-351212?atlOrigin=eyJpIjoiNTE3MTc3YTMyMTA1NDk1ZmI0ODFiYmQ3Yjg1YTM4MDEiLCJwIjoiaiJ9

**Comment by dogeared** [comment]
@albertchen-okta this can be closed

**Comment by albertchen-okta** [comment]
closing, thanks
