### ISSUE TITLE
Broken links Vue.js dev doc

### ISSUE THREAD

**Issue by nicotriballier** [okta/okta-developer-docs#1410]
When I navigate to https://developer.okta.com/docs/guides/sign-into-spa/vue/user-info/ > Vue.js > the links under "getUser()" and "Auth" are broken (404).

thanks in advance

**Comment by nicotriballier** [comment]
Note: the links under Angular and React work fine. Only the Vue.js ones are broken

**Comment by mraible** [comment]
Works for me! Can you try again?

**Comment by nicotriballier** [comment]
@mraible looks like it's fixed now, thx!
