### ISSUE TITLE
[GUIDES]: Include app-specific info next button missing

### ISSUE THREAD

**Issue by bretterer** [okta/okta-developer-docs#1426]
Missing the "next step" button on https://developer.okta.com/docs/guides/customize-tokens-returned-from-okta/create-app-profile-attribute/

<img width="1222" alt="Screen Shot 2020-09-03 at 1 59 39 PM" src="https://user-images.githubusercontent.com/1906920/92150665-bb157880-eded-11ea-82c8-52dd0ea1a6c7.png">

**Comment by dogeared** [comment]
moved to: https://oktainc.atlassian.net/browse/OKTA-368659
