### ISSUE TITLE
Broken link for factor API to upload yubikey seeds

### ISSUE THREAD

**Issue by nicotriballier** [okta/okta-developer-docs#1462]
When i go to https://developer.okta.com/docs/reference/api/factors/#enroll-factor and click on "Upload YubiKey Seed" the link is broken. The right link should be https://developer.okta.com/docs/reference/api/factors/#upload-yubikey-otp-seed

Thanks!

**Comment by dogeared** [comment]
moved to: https://oktainc.atlassian.net/browse/OKTA-368661
