### ISSUE TITLE
Broken link to configure a custom sign in page

### ISSUE THREAD

**Issue by nicotriballier** [okta/okta-developer-docs#1479]
Hi,

1) I googled Okta custom sign in page. The first result is https://help.okta.com/en/prod/Content/Topics/Settings/custom-okta-hosted-sign-in-page.htm, which mentions this link https://developer.okta.com/docs/guides/custom-hosted-signin/overview/ => that returns a 404

2) using the search feature on the developer.okta.com website, I searched for 'customize the okta-hosted sign-in page' => I got some autocomplete but no matching results were returned.

Thanks!

**Comment by susanharper-okta** [comment]
1. is now fixed.
2. is currently under discussion and we will make some changes, for sure.
