### ISSUE TITLE
Validate the Policy vs Authorization Server Policy

### ISSUE THREAD

**Issue by noinarisak** [okta/okta-developer-docs#1541]
Looking for clarity on our documentation regarding the `priority` properties between [policy/#policy-object](https://developer.okta.com/docs/reference/api/policy/#policy-object) vs [authorization-servers/#policy-properties](https://developer.okta.com/docs/reference/api/authorization-servers/#policy-properties). 

The `Policy-Object` identifies the `priority` property as NOT REQUIRED but the `Auth Server Policy Object` identifies the `priority` property is REQUIRED on creating and update. It's a little confusing and this request is related to a [PR](https://github.com/oktadeveloper/terraform-provider-okta/pull/190) in Okta Terraform Provider that I maintain.

Thanks in advance for the clarification! 😄

**Comment by robertjd** [comment]
Hi @noinarisak , we have an ask out to the team that owns these APIs for some clarification, please see OKTA-328773

**Comment by noinarisak** [comment]
Thanks, @robertjd !

**Comment by noinarisak** [comment]
hi @robertjd [OKTA-328773](https://oktainc.atlassian.net/browse/OKTA-328773) looks resolved and the original [PR](https://github.com/oktadeveloper/terraform-provider-okta/pull/190) from the Terraform repo contributors advised approach for the requester. Thanks!
