### ISSUE TITLE
API Access Management Recommended Practices

### ISSUE THREAD

**Issue by caseysoftware** [okta/okta-developer-docs#1557]
Under the Definitions under Recommended Practices, we should add notes for the Organization and Default/Custom Authorization Servers.

- The Organization (or Org) Authorization Server is designed for simple SSO using OpenID Connect or to get an access token for the Okta APIs. It does not support custom scopes, customizing the access tokens, authorization policies, or Token Inline Hooks.

- The Custom Authorization Server supports OpenID Connect and OAuth 2.0 in general. It does include custom scopes, customizing the access tokens, authorization policies, and Token Inline Hooks.

- The Default Authorization Server is the first Custom Authorization Server. It is not the same as the Organization Authorization Server.

Ref:  https://github.com/okta/okta-developer-docs/blob/master/packages/%40okta/vuepress-site/docs/concepts/api-access-management/index.md#definitions and https://developer.okta.com/docs/concepts/auth-servers/

**Comment by robertjd** [comment]
CC @jakubvul and @danielcapriceru-okta to review suggested ideas

**Comment by dogeared** [comment]
moved to: https://oktainc.atlassian.net/browse/OKTA-368664
