### ISSUE TITLE
[Guides]: Implement OAuth for Okta

### ISSUE THREAD

**Issue by noinarisak** [okta/okta-developer-docs#1572]
Add additional clarity to our following [guide](https://developer.okta.com/docs/guides/implement-oauth-for-okta/overview/) on the different types of Okta Authorization Servers for customers that are new to Okta. i.e., **Okta Org Level Authorization Server**, the **"default" Authorizations Server**, and **custom Authorizations Server**.

Customers go through the guide but do not know that his guide is requested an `access_token` from the Okta Org level and assumes that knowledge and then have to troubleshoot their steps. Possible solutions are pre-required reading on Okta Authorizations Servers before the guide.

**Comment by robertjd** [comment]
On that guide, we link to this here: https://developer.okta.com/docs/concepts/auth-servers/

Let us know if you had something different in mind?

**Comment by noinarisak** [comment]
PR #1621 address my issue. This issue can be closed.
