### ISSUE TITLE
Python SDK

### ISSUE THREAD

**Issue by gabrielsroka** [okta/okta-developer-docs#1586]
we should add info about the new 1.0 Python SDK to
https://github.com/okta/okta-developer-docs/blob/master/packages/%40okta/vuepress-site/code/python/index.md

inluding links to
https://github.com/okta/okta-sdk-python/
etc

**Comment by swiftone** [comment]
Excellent point - @bretterer, do we have any existing tickets to promote/add guides?

**Comment by bretterer** [comment]
This has already been handled via #1588
