### ISSUE TITLE
Add SAML provider note does not mach actual behavior

### ISSUE THREAD

**Issue by dziedrius** [okta/okta-developer-docs#1596]
In https://developer.okta.com/docs/guides/add-an-external-idp/saml2/configure-idp-in-okta/ there's actually useful in real world scenarios note:

> Note: When you are setting up the IdP in Okta, sometimes the Issuer, Single Sign-On URL, and Certificate aren't available from the external IdP until the metadata (the Assertion Consumer Service URL (ACS URL) and Audience URI) is uploaded to the IdP. And, the ACS URL and Audience URI values aren't available until the IdP in Okta is configured.

>We recommend that if the external IdP requires information from Okta for setup before you have that information, enter any text for the IdP Issuer URI and enter https:url for the IdP Single Sign-On URL. After you upload the metadata to the external IdP in the next step, you can edit the IdP in Okta and enter the appropriate IdP Issuer URI, IdP Single Sign-On URL, and Certificate information.

Problem is, that validation does not allow:
- to enter https:url
- leave certificate field empty

Ideally I would say UI should allow to continue without those fields or hint temporary values next to those fields (that's especially true for certificate, as can't just enter gibberish, you need to pass valid certificate, which you don't have).
Also it would make sense to add emphasis, that non of those fields will end up in metadata file from okta's side.

**Comment by jakubvul-okta** [comment]
Thanks for this @dziedrius ! We've created a ticket for this in our [internal Jira](https://oktainc.atlassian.net/browse/OKTA-358834) and we'll get it fixed ASAP.

**Comment by susanharper-okta** [comment]
@dziedrius - we have updated the note: https://developer.okta.com/docs/guides/add-an-external-idp/saml2/configure-idp-in-okta/
