### ISSUE TITLE
React: Login component not showing up

### ISSUE THREAD

**Issue by ryann254** [okta/okta-developer-docs#1599]
If you took the [Okta Sign-In Widget and react tutorial](https://developer.okta.com/code/react/okta_react_sign-in_widget/) then you may have encountered this problem. When a user clicks on the protected route he/she is directed to the right route which is **localhost:{port}/login** if you’re in local development but THEN there's no login component and the page is just blank.
After researching tirelessly and digging through the developer forum I found the only way to fix this bug is to go into your Login.js Component(Again this is if you followed the Okta Sign-In Widget and react tutorial.) Then you’ll have to remove this line from that component…

`if (this.props.authState.isPending) return null;`

That's the only way I could solve the issue.

**Comment by shuowu** [comment]
@ryann254 Thanks for reporting the issue. You can follow the [Okta React custom login sample](https://github.com/okta/samples-js-react/tree/master/custom-login) which uses a Login Component in it. Meanwhile, we'll update the code snippets in the doc with proper working sample.

Internal Ref: OKTA-342766
