### ISSUE TITLE
[Guides]: Implement Oauth for Okta Service App

### ISSUE THREAD

**Issue by noinarisak** [okta/okta-developer-docs#1608]
Issue with the following guide: https://developer.okta.com/docs/guides/implement-oauth-for-okta-serviceapp/overview/

On `Create and sign the JWT`, when you get to the step of signing the JWT and use www.jsonwebtoken.io, Step 2 is not clear what you need to paste into www.jsonwebtoken.io into the `Signing Key` box. Are we suppose to copy&paste the `Public and Private Keypair` or `Public and Private Keypair set`. Whatever the case, I abandon using jsonwebtoken.io used our best friends online 😉  tool www.jwt.io to sign my testing JWT via `x.509` PEM  private/public key.  So I can do the last step of getting access_token and finishing the guide.

Screenshot the documentation that needs more details.
![Screen Shot 2020-10-30 at 4 08 17 PM](https://user-images.githubusercontent.com/341437/98156021-ce4fcd80-1e9c-11eb-9376-7bbd774183af.png)

Screenshot `https://mkjwk.org/`. 
![Screen Shot 2020-11-04 at 1 09 31 PM](https://user-images.githubusercontent.com/341437/98157660-461ef780-1e9f-11eb-92a1-36820317e998.png)

In step 3, `For the key format, use either the default of JWT or switch to PEM, and then click Generate JWT`.  These seem to reference a feature that is no longer on jsonwebtoken.io.
![Screen Shot 2020-11-04 at 1 18 01 PM](https://user-images.githubusercontent.com/341437/98158488-99de1080-1ea0-11eb-9f44-6e62e8ce766a.png)

**Comment by noinarisak** [comment]
Looks like the guide updated. I will validate the new documentation.

**Comment by dogeared** [comment]
fyi @noinarisak - check out https://token.dev. It's the replacement for jsonwebtoken.io. Open a developer doc Jira if you find new issues. Thanks!
