### ISSUE TITLE
Wrong error when calling the management api

### ISSUE THREAD

**Issue by g1patil** [okta/okta-developer-docs#1622]
I was making an api call to create a rule in given auth server and access policy.  My payload had the wrong grant types. But when I see the error from Okta it was not very specific.
Ex. 

my shortend payload with wrong grant type . 

"conditions": {
    "grantTypes": {
      "include": [
          "client-credentials"
      ]
    },
    "scopes": {
      "include": [
        "scope:security:okta:access-management:rules:read"
      ]
    }
  },

Okta error : 

{
    "errorCode": "E0000001",
    "errorSummary": "Api validation failed: conditions.people",
    "errorLink": "E0000001",
    "errorId": "oaej1XXQlk6SbCEFIkBzAge-A",
    "errorCauses": [
        {
            "errorSummary": "conditions.people: At least one of ''conditions.people.users.include'' or ''conditions.people.groups.include'' must contain a valid user or group when ''conditions.grantTypes'' contains one or more of [authorization_code, implicit, password]."
        }
    ]
}

I was thinking that if we get more specific error. I mean the provided grant type( client-credentials ) was not in the allowed values ( authorization_code, implicit, password, client_credentials ).

I mixed up - with _ if you see.

**Comment by nickgamb** [comment]
Hello! Thank you for sharing your feedback on this. This repo is really for documentation issues only and it seems that what you are describing is an enhancement request for Okta's core platform API's. To submit such a request you should do so through the Ideas Board. https://support.okta.com/help/s/article/Okta-Ideas-Step-by-Step-Guide?language=en_US.
