### ISSUE TITLE
Missing Identity Provider Social Authentication Token object API path and sample request

### ISSUE THREAD

**Issue by MaxChal** [okta/okta-developer-docs#1638]
I have a use case where I would need the Identity Providers access and refresh token to access the Identity providers API.

This item in the documentation seems to be what I need, however, the documentation is not complete. It does not contain the API endpoint and it does not contain the sample request.

https://developer.okta.com/docs/reference/api/idps/#identity-provider-social-authentication-token-object

![image](https://user-images.githubusercontent.com/8027809/99450607-d6703880-2985-11eb-8fdc-12aa23820b1a.png)

**Comment by jakubvul-okta** [comment]
Hi @MaxChal is this what you're looking for? https://developer.okta.com/docs/reference/api/idps/#social-authentication-token-operation

**Comment by jakubvul-okta** [comment]
As I believe this is the information you're looking for @MaxChal , I'm going to close this issue. Let me know if that's not correct!
