### ISSUE TITLE
Undocumented schema update API capability

### ISSUE THREAD

**Issue by rdorn** [okta/okta-developer-docs#1649]
It seems that at least one capability is missing from this enumeration [Update schema](https://developer.okta.com/docs/reference/api/schemas/#update-user-profile-schema-property)

>Updates one or more custom User Profile properties in the schema, a permission for a User Profile base property, or the nullability of the firstName and lastName properties in the User Profile base schema.

It can also modify the `Format restriction` attribute of the `login` base property (`"format":"email"` or `"pattern": "[a-zA-Z0-9]+"` for example)

**Comment by dogeared** [comment]
internal tracking at: https://oktainc.atlassian.net/browse/OKTA-368666

**Comment by annejuan-okta** [comment]
Hi @rdorn , just letting you know that we've closed out this issue:

> the `pattern` property was added to the API reference at some point since this ticket was opened. the `format` property can only be updated on custom attributes. The behaviour is illdefined and gated, we won't add further docs.
