### ISSUE TITLE
Remove or update the PySAML2 guide

### ISSUE THREAD

**Issue by jpf** [okta/okta-developer-docs#1650]
It's time to either remove or update this PySAML2 guide: https://developer.okta.com/code/python/pysaml2/

Reasons why it should be removed:

- PySAML2 appears to only work with Python 2 and Python 2 is now deprecated
- The PySAML2 library makes use of the `xmlsec1` which is an inherently insecure way to validate SAML assertions
- That guide was written before Okta supported OpenID Connect
- We should be encouraging developers to use OpenID Connect instead of SAML

Reasons why it should be updated:
- Leaving it up would make it easier to tell people to use OpenID Connect instead
- SAML is never going to go away and perhaps some people would appreciate our help with doing that in Python?

My vote is to replace the page with a big notice saying that we encourage use of OpenID Connect instead, with links to blog posts showing how to do that, and then perhaps a year later, removal of the page entirely.

**Comment by nickgamb** [comment]
Lets keep the doc for the folks who need it, add a short note discussing SAML vs OIDC, and get a python 3 version on the backlog.

**Comment by dogeared** [comment]
moved to: https://oktainc.atlassian.net/browse/OKTA-368668
