### ISSUE TITLE
Numbering is not displayed on page

### ISSUE THREAD

**Issue by vijetmahabaleshwar-okta** [okta/okta-developer-docs#167]
In the following [page](https://developer.okta.com/code/rest/), steps should be indented with numbers. But they're not displayed. (**Set Up Your Environment**  section)

Looking at the source [markdown](https://github.com/okta/okta-developer-docs/blob/master/packages/%40okta/vuepress-site/code/rest/index.md), though shows that the numbers are present. Not sure what the issue is but the page is not rendered correctly.

**Comment by bretterer** [comment]
It appears that `language-content li` has `list-style:none` which needs to be updated in scss

**Comment by alexdahl-okta** [comment]
This appears to be resolved.
