### ISSUE TITLE
Inconsistent Documentation 

### ISSUE THREAD

**Issue by jamesreeder-okta** [okta/okta-developer-docs#1670]
On our OAuth2.0 Api Document page https://developer.okta.com/docs/reference/api/oidc/#userinfo, there is an inconsistency on the UserInfo requests.

The page says to use the verb **GET**, but the example shows use of the verb **POST**. Both actually work and give the same result, but this should be a **GET** request in the example.

**Comment by dogeared** [comment]
moved to: https://oktainc.atlassian.net/browse/OKTA-368672
