### ISSUE TITLE
Custom error page update to display custom error message based on condition 

### ISSUE THREAD

**Issue by 696balu** [okta/okta-developer-docs#1680]
Is there way to display the custom message if error summary is App access locked. 

Thanks,
Bala

**Comment by dogeared** [comment]
Internal tracking: https://oktainc.atlassian.net/browse/OKTA-368674

**Comment by albertchen-okta** [comment]
@696balu did you get an answer to your question yet? Next time, please try try https://devforum.okta.com/ or reach out to developers@okta.com to reach the Developer Support team.
