### ISSUE TITLE
[FEATURE] Add hyperlink for our Guides documenation

### ISSUE THREAD

**Issue by noinarisak** [okta/okta-developer-docs#1753]
When emailing references to our documentation it would really be helpful to just reference the top sections and subsections.  I attached a screenshot to help elaborate on the request.

![Screen Shot 2020-12-30 at 4 51 48 PM](https://user-images.githubusercontent.com/341437/103385504-609cd800-4ac0-11eb-841f-b59c21155345.png)

**Comment by noinarisak** [comment]
Any updates? If you point me in the write direction I can update the Markdown/VuePress and submit a PR.

**Comment by dogeared** [comment]
moved to: https://oktainc.atlassian.net/browse/OKTA-368676
