### ISSUE TITLE
org server doesn't return groups claim

### ISSUE THREAD

**Issue by gabrielsroka** [okta/okta-developer-docs#1778]
https://developer.okta.com/docs/guides/customize-tokens-groups-claim/overview/
https://developer.okta.com/docs/guides/customize-tokens-groups-claim/request-token-claim/
https://developer.okta.com/docs/guides/customize-tokens-groups-claim/add-groups-claim-org-as/
(and perhaps other pages) say
> using the Okta Org Authorization Server

and

> using both the Org Authorization Server

etc, but it doesn't work with the Org Server. this article explains why:
https://support.okta.com/help/s/article/Okta-Groups-or-Attribute-Missing-from-Id-Token?language=en_US

i don't know if it's a code bug, or a doc bug, or both.

**Comment by jakubvul-okta** [comment]
@gabrielsroka please create a Jira for this.

**Comment by albertchen-okta** [comment]
please add a JIRA to our backlog and assign to the developer doc triage handle: https://oktainc.atlassian.net/secure/RapidBoard.jspa?rapidView=365&view=planning&selectedIssue=OKTA-360200&issueLimit=100
