### ISSUE TITLE
Apps API - Idp-Initiated Login object listed under Application operations

### ISSUE THREAD

**Issue by damianharden** [okta/okta-developer-docs#1825]
Go to https://developer.okta.com/docs/reference/api/apps/#idp-initiated-login-object

The **IdP-Initiated Login object** section content appears directly underneath the **Add application** section as part of the the **Application operations** section.

I believe that the **IdP-Initiated Login object** section content belongs in the **Models** section at the bottom of the page?

**Comment by dogeared** [comment]
moved to: https://oktainc.atlassian.net/browse/OKTA-368677
