### ISSUE TITLE
Link checker not finding 404's

### ISSUE THREAD

**Issue by robertjd** [okta/okta-developer-docs#186]
On this page:

https://developer.okta.com/docs/api/resources/oidc/#token-authentication-methods

There is a link to:

https://developer.okta.com/docs/api/resources/oidc/oauth-clients#json-web-key-set

That page doesn't exist, I would expect our link checker to fail on this

**Comment by wayneearl-okta** [comment]
Researching this. The link checker seems to be confused by relative links. I am hoping it is a configuration issue...

**Comment by wayneearl-okta** [comment]
the root cause of this relates to some anomalies with the local (`yarn dev`) server that is tested against. we will need to revisit the way we're doing link checking.

**Comment by dogeared** [comment]
@wayneearl-okta - is this still an issue?

**Comment by dogeared** [comment]
https://oktainc.atlassian.net/browse/OKTA-351213?atlOrigin=eyJpIjoiOWJiMjZkZDAwYjU5NGZkODhiMWU4MGI3NDE0NGYxZWUiLCJwIjoiaiJ9
