### ISSUE TITLE
"Send Code" button on 2FA login dialog is poorly positioned.

### ISSUE THREAD

**Issue by dumptruckman** [okta/okta-developer-docs#1914]
Myself and several of my coworkers agree that the position of the "Send Code" button is not ideal. It is currently in line and to the right of the input box for the code itself. Despite knowing that I am looking for this button I am often looking in the wrong place as my instinct tells me that the button next to the input is how I submit the code after entering it. We think that having the button be above this input, perhaps below the phone number the code will send to, would be a better position. 

I'm not sure this is the right forum for such feedback but maybe it will at least help it get to the right place!

**Comment by albertchen-okta** [comment]
Thanks @dumptruckman this is a totally valid UX critique (which I've heard before).

I will funnel this to our sign-in widget team's roadmap.
