### ISSUE TITLE
Links to guides and guide sections

### ISSUE THREAD

**Issue by nbarbettini** [okta/okta-developer-docs#202]
A `GuideLink` component would be a big help for guide authors. There are a few scenarios to support:

#### 1. Linking to a specific section of the current guide

For example:

```md
Make sure you have [completed the prerequisites](/guides/sign-into-spa/-/before-you-begin).
```

The current stack selection should be preserved. The link text should be the title of the guide section, unless specified by the author.

#### 2. Linking to a specific section of a guide from a different guide, or from another area of documentation

```md
See [Use the Access Token](/guides/sign-into-spa/-/use-the-access-token) in the Sign Users into Your Single-Page Applications guide.
```

Because different guides have different stacks, the current stack selection does not need to be preserved. The link text should be the title of the guide section, unless specified by the author.

#### 3. Linking to the beginning of a guide, either from another guide or from another part of documentation

```md
Read the [Sign Users into Single-Page Applications](/guides/sign-into-spa) guide.
```

The current stack selection does not need to be preserved. The link text should be the title of the guide, unless specified by the author.

**Comment by bretterer** [comment]
What would you want the component to look like and how would you want it to be used?  What is the purpose here instead of just doing standard markdown links?

**Comment by swiftone** [comment]
> 1. Linking to a specific section of the current guide

This can be done as a relative link `[Name of Section](name-of-section/)` and it should work fine, including preserving the current stack selection.

**Comment by nbarbettini** [comment]
> What would you want the component to look like and how would you want it to be used?

Like `<GuideLink section="before-you-begin">Start over</GuideLink>`

>What is the purpose here instead of just doing standard markdown links?

To remove the guesswork from creating Markdown links to guide content and make sure they always work.

> This can be done as a relative link 

I tried this markdown: `[previous step](define-callback/)`. It almost worked, but got me into a weird state where two sections existed in the URL (and the stack selectors were broken):

![image](https://user-images.githubusercontent.com/7525482/55988782-9d280080-5c59-11e9-849b-13aedc16fa66.png)

**Comment by swiftone** [comment]
> `[previous step](define-callback/)` 

Ah, you're having a trailing link in the guides.  Yeah, that won't fly.  If you have `http://localhost:8080/guides/sign-into-your-web-app/net/configure-packages` as the url, then `[Other](before-you-begin)` works fine...but this is different than the "everything must end in /" of the rest of the site, so that would make it `[Other](../before-you-begin)`.

I should force the guides to be one way or the other.

**Comment by nbarbettini** [comment]
@swiftone delivered fixes for this that make this a lot better (thanks!). We may need more enhancements in the future to make authoring even easier, but if so that'll be a new issue. All good in the short to medium term.
