### ISSUE TITLE
Difficulty setting up Api for Okta

### ISSUE THREAD

**Issue by Andrae-Tugboat** [okta/okta-developer-docs#2030]
Hi,

I am trying to set up Api for Okta, and it works fine with using an api key that is generated from the UI.

The difficulty I am seeing is that when I try to use oauth2 I always get a 400 error with no additional information from the `authorize` endpoint. 

Also I noticed this page has a typo for the `redirect_uri` query param in the link for the redirect
https://developer.okta.com/docs/guides/implement-oauth-for-okta/request-access-token/

Is the authorize call to the Org Authorization Server supposed to look something like this?
`https://dev-123456778.okta.com/oauth2/v1/authorize`

Any other guidance or debugging help you can provide would be very helpful.

Thanks

**Comment by jakubvul-okta** [comment]
Hi Andrae, is that the link you meant to include? I don't see `resource_uri` on that page at all.

**Comment by Andrae-Tugboat** [comment]
Sorry about that I meant `redirect_ur` is the query param being used. I updated the original post.

**Comment by Andrae-Tugboat** [comment]
I found out my problem. I had not done the first steps with creating the native app and client.Once I completed that step then everything worked as the documentation described. :+1:

**Comment by janethu-okta** [comment]
Closing this issue since nothing needs to be updated in the documentation.
