### ISSUE TITLE
Article title component

### ISSUE THREAD

**Issue by nbarbettini** [okta/okta-developer-docs#207]
Per @alexdahl-okta, this is what the top of documentation pages should look like (applies to guides and everything else):

<img width="676" alt="Screen Shot 2019-04-11 at 10 30 45 AM" src="https://user-images.githubusercontent.com/7525482/55995177-aa98b700-5c68-11e9-895c-a0e1750c9c5a.png">

We already have the Edit link (currently Edit Page), but we don't have Last Updated.

**Comment by bretterer** [comment]
We would not be able to add this information under the title.  The title of the page is part of every markdown file.

I would suggest doing this at the top right of the template file.

<img width="994" alt="Screen Shot 2019-08-23 at 3 32 16 PM" src="https://user-images.githubusercontent.com/1906920/63618911-404f3600-c5bb-11e9-8a06-e92db1bb9115.png">


Thoughts @alexdahl-okta ?

**Comment by alexdahl-okta** [comment]
This is still desired, and important as our content grows and additional levels of hierarchy are added.

The [article title component](https://github.com/okta/okta-developer-docs/blob/master/packages/%40okta/vuepress-theme-prose/components/PageTitle.vue) should include:

- the parent sub-section title, if the article is in a sub-section
- the article title, which is consistent with all appearances of the article title in navigation
- the last updated date
- an edit link

Note that this is an _article_ title. Non-article pages, such as the [docs front page](https://developer.okta.com/docs/), would not use this component for their page title.

**Comment by dogeared** [comment]
https://oktainc.atlassian.net/browse/OKTA-351217?atlOrigin=eyJpIjoiYjA1Y2ViMjQwNDc0NDEyZjliMzNjNmRhZDUwNThiOTEiLCJwIjoiaiJ9

**Comment by dogeared** [comment]
put detail in Jira ticket
