### ISSUE TITLE
confusing statement in 'build sso integration' - guide

### ISSUE THREAD

**Issue by MPuhakka** [okta/okta-developer-docs#2071]
**Affected page(s):**

in documentation: https://developer.okta.com/docs/guides/build-sso-integration/before-you-begin/

in github: https://github.com/okta/okta-developer-docs/edit/master/packages/@okta/vuepress-site/docs/guides/build-sso-integration/before-you-begin/index.md

**Describe the problem(s):**

The page states the following
```
Note: For OIDC app integrations intended for publication in the OIN, you must use a Web (server-side) platform with an authorization code flow.
```

Does this mean that no PKCE - based flow ( and the SPA - type application ) can be used if the intention is to publish to okta integration network?

Or does the statement mean that if web (server-side) application is chosen, then it follows that authorization code flow must be used?

Or am I missing the point entirely?

For reference, the [next page](https://developer.okta.com/docs/guides/build-sso-integration/create-your-app/) in this guide states
the following:

```
Choose either Web or SPA as the platform for your integration. OIN only publishes cloud-based SaaS apps, either traditional Web applications with a back-end or a modern browser-based SPA.
```

that seems contradictory in not being able to publish SPA - application into okta integration network

**If possible, describe a proposed fix:**

clarify the quoted statement in 'describe the problem' part

**Comment by jakubvul-okta** [comment]
Thanks for the feedback @MPuhakka ! I've passed this along to the OIN team.
