### ISSUE TITLE
Add a copy button in the language box to copy/paste code samples

### ISSUE THREAD

**Issue by laura-rodriguez** [okta/okta-developer-docs#213]
As per @nbarbettini , I added this issue after our conversation.

**Comment by nbarbettini** [comment]
All code fences on developer.okta.com must have a 📋 button that copies the contents of the code block into the clipboard. It'll make it much easier to copy and paste examples!

**Comment by dogeared** [comment]
put detail in: https://oktainc.atlassian.net/browse/OKTA-355443
