### ISSUE TITLE
Access new Group Profile attributes from claims expression

### ISSUE THREAD

**Issue by mcalello** [okta/okta-developer-docs#2136]
Looking through the documentation to see if it is possible to access our new Group profile attributes from within a claim expression, and didn't find anything.  

Is this possible now with the new EA toggled on for Group Profiles for Universal Directory?

**Comment by brianduffield-okta** [comment]
A belated reply, but yes these are available with `Groups.contains`, `Groups.startsWith`, and `Groups.endsWith`. See: https://developer.okta.com/docs/reference/okta-expression-language/#group-functions and https://developer.okta.com/docs/reference/api/groups/#profile-object

Thank you for the question and feedback.
