### ISSUE TITLE
Odd back button behavior

### ISSUE THREAD

**Issue by swiftone** [okta/okta-developer-docs#235]
One report says:

1. visit https://developer.okta.com/docs/api/resources/oauth-clients/
2. without scrolling, click `Client Application Operations` in the right nav
3. click back. this triggers a fade-in, the URL doesn't change, and you end up still at `Client Application Operations`

When I attempted to recreate, the back button wasn't even enabled - my browser history was empty.

Behavior may be different between Chrome/Safari/FF

**Comment by bretterer** [comment]
I experience going back a page all together.  ie, clicking link from issue above, clicking `Client Application Operations`, clicking back takes me back to this issue page.  

This was tested in Chrome on mac

**Comment by dogeared** [comment]
added detail to: https://oktainc.atlassian.net/browse/OKTA-355444
