### ISSUE TITLE
UUID recommendation for deviceToken

### ISSUE THREAD

**Issue by kwickramasekara** [okta/okta-developer-docs#2409]
**Affected page(s):** 
[https://developer.okta.com/docs/reference/api/authn/#device-token-best-practices](https://developer.okta.com/docs/reference/api/authn/#device-token-best-practices)

**Describe the problem(s):**
Okta recommends that we generate a UUID or GUID for `deviceToken` but [forces a character limit of 32](https://developer.okta.com/docs/reference/api/authn/#context-object). 
[Per spec](https://www.uuidtools.com/what-is-uuid), UUID has 36 characters. So we can't technically use a UUID as `deviceToken` unless we strip out the 4 dashes in UUID. 

**If possible, describe a proposed fix:**
Increase character limit of `deviceToken` or recommend an alternative for UUID.

**Comment by brianduffield-okta** [comment]
Belatedly checking this out and confirming the status. Thanks for the feedback.
