### ISSUE TITLE
Update python example for verifying ID/Access tokens (JWTVerifier is deprecated)

### ISSUE THREAD

**Issue by jketcham** [okta/okta-developer-docs#2502]
**Affected page(s):**
- ["Understand the callback route" for Python](https://developer.okta.com/docs/guides/sign-into-web-app/python/define-callback/)
  - [Source for page here](https://github.com/okta/okta-developer-docs/blob/90e1beaf3f2408add90eb0a364124d6bc3949cc4/packages/%40okta/vuepress-site/docs/guides/sign-into-web-app/define-callback/python/define-route.md)
- ["Add and configure packages" under "Protect your API" for Python](https://developer.okta.com/docs/guides/protect-your-api/python/configure-packages/)
  - [Source for page here](https://github.com/okta/okta-developer-docs/blob/90e1beaf3f2408add90eb0a364124d6bc3949cc4/packages/%40okta/vuepress-site/docs/guides/protect-your-api/configure-packages/python/configmid.md)

**Describe the problem(s):**
The `JWTVerifier` class used on this page to verify id and access tokens [is deprecated](https://github.com/okta/okta-jwt-verifier-python/blob/bff9fd3ed1a4f25d0d16dea765f82f06d0148018/okta_jwt_verifier/jwt_verifier.py#L39-L41).

**If possible, describe a proposed fix:**
The examples for verifying access and ID tokens should use the new class specific approaches (`IDTokenVerifier` and `AccessTokenVerifier`).

**Comment by brianduffield-okta** [comment]
A ticket has been created to review and address. Thanks.

**Comment by brianduffield-okta** [comment]
This guide was recently revised and addressed the `JWTVerifier` issue.
