### ISSUE TITLE
missing scopes

### ISSUE THREAD

**Issue by gabrielsroka** [okta/okta-developer-docs#2608]
https://developer.okta.com/docs/guides/implement-oauth-for-okta/scopes is missing the following scopes

path | scope
---- | -----
/api/v1/authenticators/{authenticatorId}/lifecycle/activate | okta.authenticators.manage
/api/v1/authenticators/{authenticatorId} | okta.authenticators.read
/api/v1/brands/{brandId}/themes/{themeId}/background-image | okta.brands.manage
/api/v1/brands/{brandId}/themes/{themeId} | okta.brands.read
/api/v1/captchas/{id} | okta.captchas.manage
/api/v1/captchas/{id} | okta.captchas.read
/api/v1/myaccount/directoryProfile | okta.myAccount.manage
/api/v1/myaccount/directoryProfile | okta.myAccount.read
/api/v1/org/contacts/{contactType} | okta.orgs.manage
/api/v1/org/contacts/{contactType} | okta.orgs.read

**Comment by brianduffield-okta** [comment]
Hi @gabrielsroka The scopes content is now automated and is available on our OAS3 repo: https://developer.okta.com/docs/api/oauth2/
