### ISSUE TITLE
Documentation for converting a federated user to okta user using blank provider object

### ISSUE THREAD

**Issue by brandongblack** [okta/okta-developer-docs#2612]
**Affected page(s):**
https://developer.okta.com/docs/reference/api/users/#request-example-convert-a-user-to-a-federated-user
https://developer.okta.com/docs/reference/api/users/#provider-object

**Describe the problem(s):**
The examples provided show how to convert an okta user to federated user. We had a use case to convert from federated user to okta user. However when we attempted to use the sample above with object "provider=OKTA". we get an error. However it was found, by feedback from others, that if you leave the object blank like below:
/api/v1/users/{{uuid}}/lifecycle/reset_password?provider=&sendEmail=false

This converts the user from federated to okta. 
So the problem being reported is just to explicitly document that use case and to use a blank provider parameter

**If possible, describe a proposed fix:**
Provide a second section for Example to convert a federated user to okta user and provide the sample showing the blank provider object

**Comment by brianduffield-okta** [comment]
Hi @brandongblack checked with engineering and to convert back to an Okta user you only need to call the default endpoint. That said, it's not an intuitive call and we've added a new example as you suggested. See: https://github.com/okta/okta-developer-docs/pull/4536. Closing this issue as fixed, but if there's anything else, feel free to comment.
