### ISSUE TITLE
GTM is not firing properly

### ISSUE THREAD

**Issue by zdevil** [okta/okta-developer-docs#28]
I see it in code but I believe it's not firing at all

<img width="1526" alt="Screen Shot 2019-03-18 at 4 13 15 PM" src="https://user-images.githubusercontent.com/2672415/54569656-e5c10680-4998-11e9-9f7d-55b6f16417c5.png">

**Comment by bretterer** [comment]
This is ONLY enabled when on developer.okta.com.

This was set this way from flickerbox

```
var isProduction = window.location.hostname === 'developer.okta.com';
    if (isProduction) {
      // Google analytics
      ...

      // START Google Tag Manager
      ...
      // END Google Tag Manager

      // Start Heap Analytics
      ...
      // End Heap Analytics
    }
```
