### ISSUE TITLE
Broken anchor links on https://developer.okta.com/reference/scim

### ISSUE THREAD

**Issue by albertchen-okta** [okta/okta-developer-docs#292]
Many of the anchor links in the right hand nav for `/reference/scim` do not work, and I think its because the anchor links in the article for certain sections are empty, so its not matching

For instance, the 3rd section for 

`Read Account Details: GET/users` has an anchor of https://developer.okta.com/reference/scim/#read-account-details-get-users-id 

But in the article the section link is simply: 
https://developer.okta.com/reference/scim/# 
sans the sub-section string

**Comment by bretterer** [comment]
To me, it seems that the page headers should be changed fully.

Currently the headers are 
## Create Account: POST /Users 

Where It should be something like 

```
## Create Account

<ApiOperation method="Post" url="/users />
```

Or something like this.

It is odd to me that the url and method are part of the header itself

cc: @nbarbettini

**Comment by ojaldin1** [comment]
the anchor to https://github.com/okta/okta-developer-docs/issues on the SCIM instructions is broken as well

**Comment by ojaldin1** [comment]
Correction
the anchor to http://developer.okta.com/docs/sdk/opp/javadoc/index.html on the SCIM instructions is broken as well
