### ISSUE TITLE
Use only vanilla Razor code in aspnet/aspnetcore examples

### ISSUE THREAD

**Issue by nbarbettini** [okta/okta-developer-docs#296]
In these examples: `/guides/sign-into-web-app/aspnetcore/get-user-info/`

We show classes like `dl-horizontal`, `btn-link btn-xs`, and `data-clipboard-text` which are specific to Bootstrap and clipboard.js. That's what we use in the example app, but we should keep the guide sample code as plain and simple as possible.

@laura-rodriguez Can you modify the guide sample code to show only plain HTML and Razor? We can drop the "copy to clipboard" functionality.

**Comment by dogeared** [comment]
moved to: https://oktainc.atlassian.net/browse/OKTA-355446
