### ISSUE TITLE
Hardcopy Printouts

### ISSUE THREAD

**Issue by ghost** [okta/okta-developer-docs#299]
I'm noticing that when I print out a page from our site, text is cut off at the the top of each hardcopy page, i.e., a few lines of text are just missing from the hardcopy at the top of each pages. I think that what's happening is that the text is getting hidden behind the menu bar, which is repeated in the printout at the top of each page. Don't know if this has to do with my particular browser or printer, but the issue I think we should look into is whether pages print out okay, and if not can we tweak to improve that. Does the CSS stylesheet have a "@media print { .... }" section? Maybe it could set the menu bar and other navigation elements to hidden?

**Comment by dogeared** [comment]
Moved detail to: https://oktainc.atlassian.net/browse/OKTA-355447
