### ISSUE TITLE
Anchor links not working on https://developer.okta.com/docs/change-log/

### ISSUE THREAD

**Issue by bobtiernay-okta** [okta/okta-developer-docs#309]
It looks as though anchor links on https://developer.okta.com/docs/change-log/ don't add the anchor id to the url when clicking:

![image](https://user-images.githubusercontent.com/25536705/57389089-76d98000-7187-11e9-800e-f53d717bf106.png)

However right, right clicking produces the correct URL:

![image](https://user-images.githubusercontent.com/25536705/57389193-aab4a580-7187-11e9-982b-290f2bba0e97.png)

But, after scrolling the page and refreshing, the anchor is not respected. Instead the last scroll position is used for positioning.

**Comment by dogeared** [comment]
moved detail to: https://oktainc.atlassian.net/browse/OKTA-355448
