### ISSUE TITLE
Stack Selector icons and text are oppositely aligned

### ISSUE THREAD

**Issue by swiftone** [okta/okta-developer-docs#313]
This appeared after the Nim inclusion, so updates may have to be made there.

![Screen Shot 2019-05-08 at 10 53 51 AM](https://user-images.githubusercontent.com/492300/57398668-6d9ae400-7184-11e9-8af6-959b42df46f3.png)

**Comment by swiftone** [comment]
@alexdahl-okta Thoughts?

**Comment by alexdahl-okta** [comment]
@swiftone Hmm I'm not seeing this on the live site. Is this on a specific page/branch/browser?

**Comment by swiftone** [comment]
@alexdahl-okta - Odd, you are correct.  Now it's not happening for me, even in the same page/branch/browser, so SOMETHING fixed it.   Closing as delusional.
