### ISSUE TITLE
Okta can't find appuser.email or appuser.id for Github IDP

### ISSUE THREAD

**Issue by kartik-yb** [okta/okta-developer-docs#3174]
Hello everyone, I am facing some problems in trying to configure GitHub as a Social Identity Provider on Okta. Please let me know if this is not the correct place to ask this question. Thanks in advance.

### The Problem
I set up the IDP, Client App and Profile Mapping as mentioned [here](https://developer.okta.com/docs/guides/social-login/github/main/). The redirection to Github works fine.

IDP Configuration
![Screenshot 2022-03-22 at 12 52 39 PM](https://user-images.githubusercontent.com/96485202/159428612-6173926d-b01c-4e38-bf49-d9ed352ca41e.png)

For triggering the external authentication, I redirect to the following URL:
```
https://dev-77814253.okta.com/oauth2/v1/authorize?idp={idpID}&client_id={clientID}&response_type=code&response_mode=query&scope=openid%20email%20profile&redirect_uri=http://localhost:8080/authorization-code/callback&state=aBcD1&nonce=h0Ck1
```
Where I have an Okta flask sample app running at localhost:8080.

Once externally authenticated however, Okta is not able to retrieve `idpuser.email`. I tried the fix as mentioned [here](https://developer.okta.com/docs/guides/social-login/github/main/#handle-users-without-email-addresses), however `idpuser.id` and `appuser.id` is being returned as null. I know this because the user that gets created in my directly is instantiated with a null@github.example.com email address.

![Screenshot 2022-03-22 at 1 00 09 PM](https://user-images.githubusercontent.com/96485202/159429631-09872f15-9498-411a-8398-6e929023a194.png)

### Possible Fix
I notice that the user created in my Okta directory has the profile URL correctly set as https://api.github.com/users/kartik-yb. Unless there's something that I have messed up in my configurations, I believe Okta should be retrieving the ID from this api and setting it on appuser.id and idpuser.id

**Comment by vanngo-okta** [comment]
Hi @kartik-yb ,
Thanks for raising this issue. Can you please post your question on the [Okta Developer Forum](https://devforum.okta.com/)?
Thank you

**Comment by kartikx** [comment]
Sure, please close this issue.
