### ISSUE TITLE
Highlighted text is invisible

### ISSUE THREAD

**Issue by nbarbettini** [okta/okta-developer-docs#324]
For some reason the highlight color is very dark, which makes dark text impossible to read:

![image](https://user-images.githubusercontent.com/7525482/57473706-507a1a00-7245-11e9-82fd-550c8f6320ce.png)

**Comment by alexdahl-okta** [comment]
Interesting, specific to code blocks.

Appears to be coming from `prism-solarizedlight.css`, which is imported from the `prismjs` package by several layouts:
- Guides.vue
- Layout.vue
- Quickstart.vue
- SectionIndex.vue

<img width="630" alt="selection" src="https://user-images.githubusercontent.com/26014482/57485086-79e77580-7246-11e9-9e19-fb324f8f48b4.png">

**Comment by alexdahl-okta** [comment]
Appears to be resolved.
