### ISSUE TITLE
http://developer.okta.com/docs/sdk/opp/javadoc/index.html

### ISSUE THREAD

**Issue by ojaldin1** [okta/okta-developer-docs#329]
The link to javadoc is broken

**Comment by bretterer** [comment]
Can you give a little more detail here?   what is broken about it, where is the link, How can I reproduce what you are seeing?

**Comment by dogeared** [comment]
@ojaldin1  - is this still an issue? If so, please give some more detail. Thanks!

(For internal: https://oktainc.atlassian.net/browse/OKTA-355452)

**Comment by chrisdmills-okta** [comment]
No response, so closing.
