### ISSUE TITLE
Guides don’t work on mobile

### ISSUE THREAD

**Issue by mraible** [okta/okta-developer-docs#348]
![0CD587E0-0AD1-44B4-8CF7-3EC5726A0059](https://user-images.githubusercontent.com/17892/57818294-7cfbcd80-7740-11e9-8bed-449ac88a22a4.png)

The guides don’t work on my iPhone X. I can’t scroll right to see the content.

**Comment by nbarbettini** [comment]
Ack, we're already tracking this and will fix the responsiveness.

**Comment by alexdahl-okta** [comment]
This should be mostly resolved. Related issues include #959, #960, #970.
