### ISSUE TITLE
In Postman 9.26.7 for Windows, the Introductory Collection Does not Import

### ISSUE THREAD

**Issue by chuckdee68** [okta/okta-developer-docs#3546]
Thank you for getting involved with Okta's Developer Docs!

> Note: If you are an Okta employee, please [clone this Jira](https://oktainc.atlassian.net/browse/OKTA-250417) instead of opening a GitHub issue.

Please provide the following information so that we can act on your feedback.

**Affected page(s):**
https://developer.okta.com/code/rest/#set-up-your-environment

**Describe the problem(s):**
The collection at https://developer.okta.com/docs/api/postman/example.oktapreview.com.environment fails with *Error Importing: Format Not Recognized*

**If possible, describe a proposed fix:**

We will do our best to respond to you within 2 working days.

**Comment by brianduffield-okta** [comment]
@chuckdee68 Thanks for pointing out this issue. Our team will review and get back to you shortly.

**Comment by brentschaus-okta** [comment]
@chuckdee68 Hi there. I just tested importing the collection and didn't have an issue. However, if I include the period that ends the sentence with the URL (`https://developer.okta.com/docs/api/postman/example.oktapreview.com.environment.`), I receive an error message. Can you try this URL again? `https://developer.okta.com/docs/api/postman/example.oktapreview.com.environment`

**Comment by chuckdee68** [comment]
Without the . I still get the error.

![image](https://user-images.githubusercontent.com/763834/185207855-e9e7327a-44b9-4bf5-b73e-a9b57c9bb427.png)

![image](https://user-images.githubusercontent.com/763834/185207989-4320961b-528f-479b-bed1-876ae6c761ff.png)

**Comment by brianduffield-okta** [comment]
@chuckdee68 Hi, I also was able to import the environment using Postman (v.9.28.2) on a Windows 10 machine with no issue. Looking online, I did see some suggestions that virus protection software may interfere with the import. You can also review the Postman help.

However, this step shouldn't stop you from testing Okta API collections with Postman. You can set up your environment manually (see: https://learning.postman.com/docs/sending-requests/managing-environments/#creating-environments) and create, at minimum, the following two environment variables: `url` = https://{yourOktaDomain} and `apikey` = your generated API token (https://developer.okta.com/docs/guides/create-an-api-token/main/#create-the-token). Depending on the collection you're testing, you simply need to add any other variables to your environment (visible in the endpoint path). Hope this helps.

**Comment by chuckdee68** [comment]
I found a way around it. I downloaded the file at that location and imported as file instead of from the url. Just letting you know in case anyone comes to you with the same problem on the latest postman.
