### ISSUE TITLE
6ovnzz7eqh2wea327yd7g9fgb7h05p.burpcollaborator.net.iad.github.net

### ISSUE THREAD

**Issue by sskika** [okta/okta-developer-docs#3659]
6ovnzz7eqh2wea327yd7g9fgb7h05p.burpcollaborator.net.iad.github.net

**Comment by sskika** [comment]
> 6ovnzz7eqh2wea327yd7g9fgb7h05p.burpcollaborator.net.iad.github.net

m8v3jfruaxmcyqnirexn0pzwvn1hp6.burpcollaborator.net.iad.github.net

**Comment by brianduffield-okta** [comment]
Closing this issue as per: https://github.com/okta/okta-developer-docs/pull/3660
