### ISSUE TITLE
Multiple sign-up pages?

### ISSUE THREAD

**Issue by mcandre** [okta/okta-developer-docs#377]
What is the difference between these two developer sign-up pages?

* https://developer.okta.com/signup/
* https://www.okta.com/developer-sign-up/

Is the latter intended for more of a shared resource?

**Comment by nbarbettini** [comment]
Hey @mcandre! Sorry I didn't see your question here earlier. For future reference, you're likely to get a faster response here: https://devforum.okta.com

There isn't actually a difference as far as I know. It's just marketing for two different audiences. https://developer.okta.com/signup is our canonical URL for creating an Okta developer account.

Cheers!
