### ISSUE TITLE
yarn dev produces a blank page

### ISSUE THREAD

**Issue by nbarbettini** [okta/okta-developer-docs#378]
I've seen multiple reports of folks running `yarn`, `yarn dev` without errors, but not seeing any page content rendered. Instead, a blank colored page is displayed and the site doesn't work.

Not sure if it is version-related, but so far affected users have been using:
```
yarn --version
1.15.2
node --version
v8.11.1
```

This is what is displayed:
<img width="1594" alt="Screen Shot 2019-05-22 at 11 56 31 AM" src="https://user-images.githubusercontent.com/7525482/58287177-396b1a00-7d65-11e9-9f6c-37fbdecd25af.png">

**Comment by bretterer** [comment]
Cannot reproduce
