### ISSUE TITLE
Error: unable to get local issuer certificate

### ISSUE THREAD

**Issue by nbarbettini** [okta/okta-developer-docs#379]
Depending on the local environment, some users get this message when running `yarn [install]`:

```
error An unexpected error occurred: " [...] unable to get local issuer certificate".
```

This happens when the local machine is configured to use a cafile that overrides the system/default CA. For example, when a local root CA is trusted for internal packages.

**Comment by nbarbettini** [comment]
What I've seen work is:

```
mv ~/.npmrc ~/.npmrcbk
```

Then, after you are done working with this repo:

```
mv ~/.npmrcbk ~/.npmrc
```

This is just a temporary solution, we're searching for a better one 🙂 Related to: https://github.com/yarnpkg/yarn/issues/6578

**Comment by dogeared** [comment]
moved to: https://oktainc.atlassian.net/browse/OKTA-355455
