### ISSUE TITLE
/factors is missing vendorName

### ISSUE THREAD

**Issue by gabrielsroka** [okta/okta-developer-docs#3805]
https://developer.okta.com/docs/reference/api/factors/#factor-properties

**Comment by brianduffield-okta** [comment]
Thanks! Have verified this, and will update.

**Comment by gabrielsroka** [comment]
also:
https://developer.okta.com/docs/reference/api/factors/#provider-type
is missing:

Provider | Description
--------- | ------------
`CUSTOM` | ...

and https://developer.okta.com/docs/reference/api/factors/#supported-factors-for-providers
is missing:

Provider | Factor Type
--------- | ------------
`CUSTOM` | token:hotp

**Comment by brianduffield-okta** [comment]
Fixed as per this PR: https://github.com/okta/okta-developer-docs/pull/3839. Closing this issue.
