### ISSUE TITLE
Right side TOC not populated during direct navigation

### ISSUE THREAD

**Issue by robertjd** [okta/okta-developer-docs#39]
Steps to reproduce:

1. visit https://vuepress-site.trexcloud.com/reference/
2. Click on any of the links that take you into an API reference section, e.g. Policy
3. See that the sidebar has no links:
![image](https://user-images.githubusercontent.com/132343/54728919-b7c8f700-4b3d-11e9-8de6-dc7fc0c90fa6.png)
4. Reload the page, now the links appear

**Comment by bretterer** [comment]
Resolved via #41
