### ISSUE TITLE
ASA docs are unclear

### ISSUE THREAD

**Issue by gabrielsroka** [okta/okta-developer-docs#3941]
https://developer.okta.com/docs/reference/api/asa/audits/

It appears that list items have `details` which are linked to the `related_objects` section. These are the ones I found so far. Is there a comprehensive list?

`details.actor`
`details.project_id` or `details.project_name` - both of these look the same even though one's called ID and one's called name
`details.server_id`
`details.client`
`details.target_user`

Is there a list of `details.type` values?

Is there a way to search/filter audits? It looks like the UI (which uses the API) can filter on `users=...`; what's the syntax for that? Are there other fields, too?

Is the max for `count` 1000?

How far back does it go? 1 year? Forever? Is there a size limit?

**Comment by gabrielsroka** [comment]
also, for https://developer.okta.com/docs/reference/api/asa/projects/#list-servers-in-a-project

what's in `instance_details` ? examples all show `null`

**Comment by gabrielsroka** [comment]
on

https://developer.okta.com/docs/reference/api/asa/service-users/#issue-a-service-user-token

this, and most other commands that do a `POST` or `PUT`, require
```
-H "Content-Type: application/json" \
```

also, this command is to create a `jwt` (since you don't have a `jwt`), you can't pass one in.

so, the full command would be
```sh
curl -v -X POST \
-H "Content-Type: application/json" \
--data '{
	"key_id": "6052868b-1b04-4a14-8288-e6496d7f2f4b",
	"key_secret": "uF0SoVBVQP/hJmQSLUZdM2a7ArYzjD8ykzvG7n4tKaOEfSErcwMUUDWpEf4Q42/HaVKPZUfILkzy/bsQFv7WRg=="
}' \
https://app.scaleft.com/v1/teams/${team_name}/service_token
```

**Comment by brianduffield-okta** [comment]
Many thanks, @gabrielsroka , for the feedback.  Created an internal ticket to track this: https://oktainc.atlassian.net/browse/OKTA-574497

**Comment by gabrielsroka** [comment]
any news?

**Comment by brianduffield-okta** [comment]
Hi Gabriel, I pinged the writer working on this ticket. Apologies for the delay.

**Comment by isaacdurham-okta** [comment]
Morning, 

Sorry for the delay on this. I've scoped out the problem and am working with our devs to get clarification on some of the Audit specific stuff. 

[List all Audit Events](https://developer.okta.com/docs/api/openapi/asa/asa/tag/audits/)
Need to reach out to devs for clarification on these items.
- **Proposed**: Include a more comprehensive list for available params in the `details` object
- **Proposed**: Include a list of available values for details.type.
- **Proposed**: Include a more comprehensive list of available filters/queries
    - I’m pretty sure we only are publicly mentioning the 4 available options. (offset, count, descending, prev)
- **Proposed**: Mention the maximum number of returned events in the description
- **Proposed**: Mention how far back entires are included in the description
    - Testing looks like there is no time limit. I’m getting results from around the time I created my Team.

[List all Servers in a Project](https://developer.okta.com/docs/api/openapi/asa/asa/tag/projects/#tag/projects/operation/ListServersForProject)
- **Proposed**: Add descriptions to items in `instance_details` object
- **Proposed**: Update example for `instance_details` object

[Issue a Service User token](https://developer.okta.com/docs/api/openapi/asa/asa/tag/service-users/)
- **Completed**: “Content-Type: application/json”: This content is now included across all endpoints.
- **Proposed**: Remove the   `-H 'Authorization: Bearer <YOUR_JWT_HERE>'` from the example request body.
    - This might take some extra work due to how we generate ASA documentation.

**Comment by isaacdurham-okta** [comment]
Unfortunately, looks like these changes won't be included until the July monthly release (~07/12). We should be able to incorporate the remaining feedback by then as well.

**Comment by isaacdurham-okta** [comment]
Changes should be live within the hour.

- [Audits](https://developer.okta.com/docs/api/openapi/asa/asa/tag/audits/)
- https://developer.okta.com/docs/api/openapi/asa/asa/tag/projects/#tag/projects/operation/ListServersForProject
- [Issue a Service User token](https://developer.okta.com/docs/api/openapi/asa/asa/tag/service-users/)

Thanks for bringing these issues up!
