### ISSUE TITLE
unable to search this repo

### ISSUE THREAD

**Issue by gabrielsroka** [okta/okta-developer-docs#3969]
i have some code that uses the GH API to search this repo's code. it had been working since Sep 2020, but it stopped working recently:
https://gabrielsroka.github.io/o4o.html
![image](https://user-images.githubusercontent.com/14354736/219491805-774cea57-e039-4b6b-a803-26473276734a.png)

source: 
https://github.com/gabrielsroka/gabrielsroka.github.io/blob/master/o4o.html

API call:
https://api.github.com/search/code?q=repo:okta/okta-developer-docs+ApiOperation+extension:md

even using the UI to search is broken.
https://github.com/okta/okta-developer-docs/search?q=okta
![image](https://user-images.githubusercontent.com/14354736/219491688-c5815666-62b4-446e-b3df-336ca3d1f32a.png)

is this a setting? does GH need to be notified?

**Comment by brianduffield-okta** [comment]
@gabrielsroka Is this still an issue? I was able to search the repo via the UI and it returned results.

**Comment by gabrielsroka** [comment]
Yes, it's still an issue with both the API and the UI. 

Are you signed in or signed out when you do it?

**Comment by brianduffield-okta** [comment]
Yes, I was signed in. Signing-out, I couldn't search. Same result with testing your API call in Postman. I have a couple messages out to our security folks to see is this is a recent config.

**Comment by gabrielsroka** [comment]
> Postman

You can even test it in the browser in an incognito window.

Thanks!

**Comment by brianduffield-okta** [comment]
@gabrielsroka Looks like this might be a github issue: https://github.com/orgs/community/discussions/44388

**Comment by gabrielsroka** [comment]
I figured it might be. Any solutions/workarounds?

**Comment by brianduffield-okta** [comment]
@gabrielsroka Github has fixed the issue. Should be working for you. I tested and it's working on my side.

**Comment by gabrielsroka** [comment]
LGTM
