### ISSUE TITLE
No documentation for plain Java

### ISSUE THREAD

**Issue by tbenbrahim** [okta/okta-developer-docs#4015]
Thank you for getting involved with Okta's Developer Docs!

> Note: If you are an Okta employee, please [clone this Jira](https://oktainc.atlassian.net/browse/OKTA-250417) instead of opening a GitHub issue.

Please provide the following information so that we can act on your feedback.

**Affected page(s):**
https://developer.okta.com/docs/guides/quickstart/main/#server-side-web-app

**Describe the problem(s):**
Spring Boot is used by 60% of Java backends according to Snyk https://snyk.io/blog/spring-dominates-the-java-ecosystem-with-60-using-it-for-their-main-applications/). Your documenation only covers Spring Boot, and leaves out the 40% of developers that are not using Spring Boot with Java. The only documentation that was of any use as a plain Java developer was the JWT verifier documentation. If I had not done multiple OAuth2 clients over the years, I would have struggled mightily with what is offered.

**If possible, describe a proposed fix:**
Provide some documentation for plain Java, or even an Oauth library like Google does. 

We will do our best to respond to you within 2 working days.

**Comment by brianduffield-okta** [comment]
@tbenbrahim thanks for the comment/request. I'll check with our developer advocate team for feedback.

**Comment by brianduffield-okta** [comment]
Hi @tbenbrahim. After consulting with our advocates, they suggest reviewing the Developer Advocate blog site for this content. See:

https://developer.okta.com/blog/2022/05/23/java-rest-api-quarkus
https://developer.okta.com/blog/2022/05/31/java-rest-api-micronaut
https://developer.okta.com/blog/2022/06/02/java-rest-api-helidon
https://auth0.com/blog/jakarta-ee-oidc/

If you're looking for servlet/JSP, we also have the following sample repo: https://github.com/okta/samples-java-servlet

I'll also forward your request for doc to our mgmt team.

**Comment by tbenbrahim** [comment]
@brianduffield-okta Thank you for the links. I am ok with just https://developer.okta.com/docs/reference/api/oidc/, because I have done many OAuth implementations over the year, and had little problem developing a servlet filter using just that page Someone starting out may not be ok with https://developer.okta.com/docs/guides/quickstart/main/#server-side-web-app, or what they come up with when googling 'okta oauth java', unless they use one of frameworks documented.
