### ISSUE TITLE
Angular tutorial is wrong - isAuthenticated is always false on the first time

### ISSUE THREAD

**Issue by panyann** [okta/okta-developer-docs#4027]
**Affected page(s):**
https://developer.okta.com/docs/guides/sign-into-spa-redirect/main/#redirect-to-the-sign-in-page

**Describe the problem(s):**
This code:
```
this.isAuthenticated$ = this._oktaStateService.authState$.pipe(
      filter((s: AuthState) => !!s),
      map((s: AuthState) => s.isAuthenticated ?? false)
);
```
Always returns false on the first time, even if the user is already logged in after page refresh, which caused infinite loop in my code (which logs in user on enter automatically).
On the first time AuthState object is returned in the crippled state with having only one property `isAuthenticated`, which is ALWAYS false. All other properties of AuthState are not yet existent for unknown to me reason.
Then the subscription triggers second time and all properties are populated (sometimes with undefined variables, if user is logged out, but all properties finally exist). Only then isAuthenticated shows the correct true/false value.

**If possible, describe a proposed fix:**
I made a workaround to fix this stupidity, by creating such a method:
```
public isAuthenticated() {
    return this.oktaStateService.authState$.pipe(
        filter((s: AuthState) => {
          console.log('isAuthenticated()');
          console.log(s);
          return s.hasOwnProperty('accessToken')} ), // checking if one of the properties in object exists
        map((s: AuthState) => s.isAuthenticated) // returning correct bool if above is true
      );
  }
```
It checks if `accessToken` property exists on AuthState object (even if it's undefined) and only then returns `isAuthenticated` value.

Would be good if you fixed the documentation and how the `authState$` event works.

**Comment by brianduffield-okta** [comment]
@panyann Thanks for the feedback. I'll contact our Angular dev advocate to review and confirm.

**Comment by alisaduncan** [comment]
Hi there @panyann!

Thanks for your feedback. I'm sorry to hear you are experiencing some problems.

I tried recreating the looping you're seeing by running the sample project the documentation is based on, and I'm not seeing it. I also tried spinning up a new Angular application with the latest versions of the Okta SDKs just in case something changed in the SDK that might have affected the documentation, and I'm not seeing it there either. I tried logging in and then refreshing the page.

The documentation uses the sample project linked below. Would you mind comparing it to your project so we can figure out what's going on? Alternatively, if you don't mind pushing the changes you have so far into a repo, I can check it out.

[https://github.com/okta-samples/okta-angular-quickstart](https://github.com/okta-samples/okta-angular-quickstart)

**Comment by panyann** [comment]
Sorry for the confusion, I'm explaining now.
I used the Angular tutorial from the documentation for my company's project. However the requirement was to automatically log in user on the start up of the application, which is not part of your tutorial. In your tutorial user needs to click something to log in.

So I made a code like this in the app.component.ts, basing on what tutorial says:
(I just moved your Okta methods from app.component.ts to the separate service called OktaService to make it look nicer)

```
this.oktaService.isAuthenticated$.subscribe(isAuth => {

      if(isAuth == false) {
        this.oktaService.signIn();
      }
      else {
        this.router.navigate(['/history']);
      }
    });
```

The above code will cause infinite loop, because `isAuthenticated$` always returns false on the first usage and signIn() with page refresh will **always** happen.

`isAuthenticated$` is being made like in your tutorial:
```
this.isAuthenticated$ = this.oktaStateService.authState$.pipe(
      filter((s: AuthState) => !!s),
      map((s: AuthState) => s.isAuthenticated ?? false)
    );
```

That means that `isAuthenticated$` is lying about the real state of the user, because he is already logged in, but it returns false on the app start.

Please tell me if you have more questions, I will try to help.

**Comment by alisaduncan** [comment]
Thanks for the clarification @panyann.

It sounds like what you're trying to set up is beyond the scope of the quickstart tutorial. Would you mind posting this question to our [DevForum](https://devforum.okta.com/) instead?

https://devforum.okta.com/

This way, other devs will benefit from seeing these questions and responses, and you'll have better and quicker access to our developer support staff, who also have a lot more knowledge about the SDK. In the meantime, I'll try a few things to see if I can offer some possible options as a response ASAP. The `oktaStateService.authState$` is a `BehaviorSubject` that defaults to false, so we'll think of a way through that for your specific need.

Let me know if that doesn't work for you. Otherwise, feel free to post your question there, then you can either comment on this issue with your post link, or I'll watch it on the forum.

**Comment by brianduffield-okta** [comment]
Thanks @alisaduncan ! @panyann if you have any further questions, please post on the [devforum](https://devforum.okta.com/) or reopen this post.
