### ISSUE TITLE
Instructions for Vue.js sample src/config.js file is not correct

### ISSUE THREAD

**Issue by thecoops** [okta/okta-developer-docs#4158]
**Affected page(s):**
https://developer.okta.com/docs/guides/sign-into-spa-redirect/vue/main/
Instructions for Vue.js

**Describe the problem(s):**
Under the "Configure your app" section there's a sample **src/config.js** file to define your configuration settings.

> export default {
>   oidc: {
>     clientId: '${yourClientID}',
>     issuer: 'https://${yourOktaDomain}/oauth2/default',
>     redirectUri: window.location.origin + '/login/callback',
>     scopes: ['openid', 'profile', 'email']
>   }
> }

**incorrect line:** 

> issuer: 'https://${yourOktaDomain}/oauth2/default',

**Proposed fix:**

> issuer: 'https://${yourOktaDomain}',

**P.S. Another helpful hint would be to add this additional line:**

> postLogoutRedirectUri: window.location.origin + '/${yourPage}',

postLogoutRedirectUri: Specifies the url where the browser should be redirected after [signOut](https://github.com/okta/okta-auth-js#signout). This url must be listed in your Okta application's [Logout redirect URIs](https://github.com/okta/okta-auth-js#logout-redirect-uris). If not specified, your application's origin (window.location.origin) will be used.

**Comment by brianduffield-okta** [comment]
@thecoops Thanks for the post, Mike. The issuer line does look incorrect, but I'll forward to our VuePress advocate to confirm and update.

**Comment by brianduffield-okta** [comment]
@thecoops I'm closing this issue based on feedback from our developer advocate, but if you have any other concerns, please comment or check the dev forum for info: https://devforum.okta.com/
