### ISSUE TITLE
Incorrect reference to Inline Token Hooks

### ISSUE THREAD

**Issue by dvladoz** [okta/okta-developer-docs#418]
The content in the following link makes reference to Inline Token Hooks, when it should be Inline Import Hooks

https://developer.okta.com/use_cases/inline_hooks/import_hook/import_hook/#supported-commands

**Comment by nbarbettini** [comment]
Thanks @dvladoz! Fixed in https://github.com/okta/okta-developer-docs/pull/451

For small typos like this, you are also welcome to click "Edit Page" at the top of any page and submit a fix that way. If you wish 😄
