### ISSUE TITLE
define regex

### ISSUE THREAD

**Issue by gabrielsroka** [okta/okta-developer-docs#4187]
https://developer.okta.com/docs/reference/okta-expression-language/#conditional-expressions

defines `matches` but:
1. says it's deprecated. will it be replaced by something else?
2. doesn't define which regex it uses -- there are many flavors
3. should say that it's both case-sensitive and matches from beginning to end, ie, ^ and $ (beginning and end) are unnecessary
4. etc

**Comment by brianduffield-okta** [comment]
Thanks, will create a ticket for this one. https://oktainc.atlassian.net/browse/OKTA-617163

**Comment by timhowie-okta** [comment]
Discussed with the team - matches is strictly deprecated. One developer suggested using string operators that are better-suited to most use cases.

**Comment by gabrielsroka** [comment]
deprecated, but to be replaced with something else? when will it be removed?

string operators won't cut it -- they're definitely not "better-suited" !!!

there's been OEL features deprecated for years, but they're still documented. and they haven't been removed.

**Comment by timhowie-okta** [comment]
Hi Gabe - how are you using matches? I can pass along what you're trying to accomplish to the developers and see what they suggest.

**Comment by gabrielsroka** [comment]
> Gabe

Please call me Gabriel.

I've posted about `matches` several times on https://macadmins.slack.com -- a channel with 3,000 Okta customers. eg

```
user.state matches 'AL|AK|AS|AZ|AR|CA|CO|CT|DE|DC|FM|FL|GA|GU|HI|ID|IL|IN|IA|KS|KY|LA|ME|MH|MD|MA|MI|MN|MS|MO|MT|NE|NV|NH|NJ|NM|NY|NC|ND|MP|OH|OK|OR|PW|PA|PR|RI|SC|SD|TN|TX|UT|VT|VI|VA|WA|WV|WI|WY'
```

```
user.title matches '.*Manager.*'
```

**Comment by timhowie-okta** [comment]
My apologies Gabriel.

I've passed these on to the team so they can look into it.

**Comment by timhowie-okta** [comment]
Hi Gabriel, here's the information that I've received:

Thanks for taking the time to engage and help with examples. We are investigating how we can reintroduce matches that meet the performance goals we are targeting. Until that time, existing matches expressions will not be affected.
