### ISSUE TITLE
I want to call the okta /user/verify_password api interface to verify the password. How to construct the _xsrfToken parameter? Is it obtained through the interface or constructed through other parameters? I hope you can guide me in this parameter construction process. Thank you.

### ISSUE THREAD

**Issue by micro-collab** [okta/okta-developer-docs#4422]
Thank you for getting involved with Okta's Developer Docs!

> Note: If you are an Okta employee, please [clone this Jira](https://oktainc.atlassian.net/browse/OKTA-250417) instead of opening a GitHub issue.

Please provide the following information so that we can act on your feedback.

**Affected page(s):**

**Describe the problem(s):**

**If possible, describe a proposed fix:**

We will do our best to respond to you within 2 working days.

**Comment by micro-collab** [comment]
Okta setting module Modifies personal information /user/profile/edit/person_info interface How to obtain the _xsrfToken parameter required for request through the okta interface? , what are the generation rules if this field is generated from other fields? Thank you for the details

**Comment by brianduffield-okta** [comment]
@micro-collab Thanks for your posting. Your best option is to try our dev forum: https://devforum.okta.com/

Alternatively, try our Developer Advocates blog: https://developer.okta.com/search/#q=xsrf for several blog posts.

**Comment by micro-collab** [comment]
thanks  you

**Comment by brianduffield-okta** [comment]
Closing as not a specific documentation fix.
