### ISSUE TITLE
Formatting error in https://github.com/okta/okta-developer-docs/..../docs/concepts/policies/index.md

### ISSUE THREAD

**Issue by ashish-logmaster** [okta/okta-developer-docs#4481]
Please provide the following information so that we can act on your feedback.

**Affected page(s):**
https://github.com/okta/okta-developer-docs/blob/master/packages/%40okta/vuepress-site/docs/concepts/policies/index.md#policy-evaluation-based-on-authentication-pipelines

**Describe the problem(s):**
There seems to be some formatting error in this section of the document

**If possible, describe a proposed fix:**
Update document to fix the formatting error

We will do our best to respond to you within 2 working days.

**Comment by brianduffield-okta** [comment]
@ashish-logmaster Thanks for the feedback! Yes, this markdown needs updating. Will address this right away.

**Comment by brianduffield-okta** [comment]
Thanks, again, for pointing this out. This fix is now live. https://developer.okta.com/docs/concepts/policies/#policy-evaluation-based-on-authentication-pipelines
