### ISSUE TITLE
Document Okta API type coercion 

### ISSUE THREAD

**Issue by exitcode0** [okta/okta-developer-docs#4483]
Thank you for getting involved with Okta's Developer Docs!

**Affected page(s):**
- [https://developer.okta.com/docs/reference/core-okta-api/](https://developer.okta.com/docs/reference/core-okta-api/)
- [https://developer.okta.com/docs/api/](https://developer.okta.com/docs/api/)

**Describe the problem(s):**

If a user omits or provides incorrect data to the Okta API
The Okta API will either fall back to defaults or it will attempt to perform type coercion
I think some of the former is documented, but I believe the latter is undocumented?

**If possible, describe a proposed fix:**

It would be good to have documentation around how Type Coercion works in the Okta API
I'd imagine if this is performed by Okta's API gateway this should be consistent for all Okta APIs

**Comment by brianduffield-okta** [comment]
Hi @exitcode0 I'll create an internal ticket to track this request. Thanks for the post.

**Comment by brentschaus-okta** [comment]
Hi @exitcode0 , I'm looking into this issue for you.

The SME I'm chatting with doesn't believe we have an API gateway with any type coercion/validation.

Do you have a specific API in mind? What specific type coercion are you seeing? We understand that, typically, if you enter a wrong type the API rejects it with a 400 error message.

**Comment by exitcode0** [comment]
I created this over a year ago, I don't recall what issue I was running into at the time
We can close this out and I'll create a new issue if I run into another instance of this
