### ISSUE TITLE
Okta Syslog Event Types - CSV export / download 

### ISSUE THREAD

**Issue by exitcode0** [okta/okta-developer-docs#4503]
Thank you for getting involved with Okta's Developer Docs!

**Affected page(s):**
- https://developer.okta.com/docs/reference/api/event-types/

**Describe the problem(s):**
It wasn't clear to me if / where I could export this information for evaluation
I ended up having to web scrape the page to get the data into a CSV

**If possible, describe a proposed fix:**
ideally the page should have a CSV export / download button or otherwise link of to the a source `.md` file or similar in this repo (I looked for this as well, if it exists I had some trouble finding it

**Comment by brianduffield-okta** [comment]
Hi @exitcode0 Thanks for the feedback. This page is automated, somewhat, and built by a VuePress script. The source data is available in JSON format on our repo: [https://github.com/okta/okta-developer-docs/tree/master/packages/%40okta/vuepress-site/data/event-types.json](https://github.com/okta/okta-developer-docs/tree/master/packages/%40okta/vuepress-site/data/event-types.json). This content is updated monthly.

I like the idea of creating a CSV export/download button, and will open a ticket for our tools team for review. Thanks!
