### ISSUE TITLE
Broken anchor link

### ISSUE THREAD

**Issue by nbarbettini** [okta/okta-developer-docs#477]
The link to: https://developer.okta.com/docs/reference/api/users/#user-oauth-2-0-token-management-operations
from: https://developer.okta.com/docs/reference/api/authorization-servers/#response-example-25

is slightly incorrect, because the format of the `#anchor` changed. Can we update the link?

**Comment by susanharper-okta** [comment]
Resolved: https://github.com/okta/okta-developer-docs/pull/478
