### ISSUE TITLE
missing okta self scopes

### ISSUE THREAD

**Issue by RyAndrew** [okta/okta-developer-docs#4970]
**Affected page(s):**
https://developer.okta.com/docs/api/oauth2/

**Describe the problem(s):**
missing scopes

**If possible, describe a proposed fix:**
add scopes
- okta.authenticators.manage.self
- okta.users.manage.self
- okta.users.read.self

**Comment by brianduffield-okta** [comment]
Thanks, @RyAndrew , for posting the issue. I'll forward to engineering and get this addressed.

**Comment by brianduffield-okta** [comment]
These scopes are now added: [https://developer.okta.com/docs/api/oauth2/](https://developer.okta.com/docs/api/oauth2/ ). Thanks again for raising the issue. Closing as fixed.
