### ISSUE TITLE
Missing API Scopes

### ISSUE THREAD

**Issue by exitcode0** [okta/okta-developer-docs#4975]
Thank you for getting involved with Okta's Developer Docs!

## **Affected page(s):**
- https://developer.okta.com/docs/api/openapi/okta-management/guides/roles/#permission

## **Describe the problem(s):**
Some of the newer API Scopes are missing e.g `okta.apps.clientCredentials.read`

## **If possible, describe a proposed fix:**
My understanding is that these docs are generated from the Open API Spec
If i'm correct about that, the likely cause here is that the Open API Spec has fallen behind again

**Comment by vanngo-okta** [comment]
Hi @exitcode0 , the Permissions list is updated: https://developer.okta.com/docs/api/openapi/okta-management/guides/roles/#permissions
Thanks for raising this issue!
