### ISSUE TITLE
Unable to turn on SCIM via the okta API from reading the docs

### ISSUE THREAD

**Issue by ramatherDash** [okta/okta-developer-docs#5130]
Hello everyone! 😃 

I have been reading through the okta documentation looking for a way to enable SCIM provisioning for SAML SSO apps via your API, and I am having trouble enabling SCIM via the API using both the create app and update app endpoints. 
`https://{yourOktaDomain}/api/v1/apps`

On [your documentation](https://developer.okta.com/docs/api/openapi/okta-management/management/tag/Application/#tag/Application/operation/replaceApplication) `features` seems to be listed as a changeable property, however, when I try to create an app using the API with SCIM enabled and I pass the following to the Features key

```
"features": [
        "SCIM_PROVISIONING"
    ],
```
The SSO app is created but the `features` key is just an empty array. When I try to do a put request and update the `features` key with the “SCIM_PROVISIONING” feature, the request is successful, but the `features` key is still empty and SCIM is not enabled for the app.

Is it even possible to enable SCIM provisioning via the API as the documentation seems to suggest, or is this value not updatable via the API?

**Comment by annejuan-okta** [comment]
Thanks for letting us know about your issue @ramatherDash. I've followed up with our team and will get back to you when we have more info to share.

**Comment by ramatherDash** [comment]
Hello @vanngo-okta,
Thank you for your quick reply.
I am trying to turn on SCIM provisioning for a custom SAML based SSO app. So then this would be impossible, correct?

**Comment by ramatherDash** [comment]
I think it would be easier if I explained my use case for turning on SCIM via the API.

I am looking for a way to automate the confidential SSO and SCIM setup flow with my company's web extension for testing purposes. I want to be able to simulate, via an automated test, the flow that an okta SSO admin would go through when turning on SCIM provisioning for their okta app. I have already automated the SSO setup flow via your APIs, however, as seen above, I am having trouble with setting up SCIM.

Would I need register our application in the OIN for this to work?

**Comment by vanngo-okta** [comment]
Hi @ramatherDash, if you want to enable SCIM provision to your custom app, I don't think that's possible through the API. 
If you already created an SSO app, you can go through the Admin Console to enable provisioning: https://help.okta.com/oie/en-us/content/topics/apps/apps_app_integration_wizard_scim.htm. 

If you want to test enabling SCIM via the API (as a simulated test case), you can try one of the [SCIM test apps](https://www.okta.com/integrations/?search=SCIM%202.0%20Test%20App) from the OIN (SCIM 1.1 or SCIM 2.0) . Although these schemas aren't document in the API references, you can create one in the Admin Console and do a GET to see what you need to configure. 

Apps in the OIN are public to the Okta ecosystem, so you need to ensure that your app is ready to share. When you [submit your app to the OIN](https://developer.okta.com/docs/guides/submit-app-overview/), it goes through a verification process before it can be listed in the OIN catalog.

**Comment by ramatherDash** [comment]
Thank you for your detailed response.

Is there an API endpoint I could use to create one of the SCIM test apps? 

Also, if I go through the process to submit an app to the OIN, will I then be able to create an apps using that "template" via API calls?

**Comment by vanngo-okta** [comment]
Hi @ramatherDash,
Sorry for the delay. I got confirmation that you can't enable SCIM provisioning with the API for apps not listed in the [Application Connections](https://developer.okta.com/docs/api/openapi/okta-management/management/tag/ApplicationConnections/) API (so only Org2Org, Zscaler, Google, Microsoft, Slack, and Zoom).
You can only enable SCIM provisioning for your custom app through the UI (Admin Console).
Even if you submit your SCIM integration to the OIN, you still can't enable provisioning for your app through the API.

I have submitted a bug report for the `features` property (it shouldn't be in the request payload if it's not editable). Thank you for bringing this issue to our attention!

**Comment by ramatherDash** [comment]
Hello @vanngo-okta,
Okay, thank you very much. I hope you have a nice week!
