### ISSUE TITLE
Obsolete Reference in Android Quickstart

### ISSUE THREAD

**Issue by overciv** [okta/okta-developer-docs#647]
Hello, the android quickstart show a link to the outdated Android SDK and should be updated with the new one:
https://developer.okta.com/quickstart-fragments/android/default-example/#add-okta-appauth-to-your-android-project

It is misleading and it's not evident to detect that it is the wrong one before it's too late.

The new SDK is : https://github.com/okta/okta-oidc-android

**Comment by bretterer** [comment]
@overciv thank you for reporting this issue on our docs, we have confirmed this issue. We will be checking through the whole quickstart to make sure that there are no other updates that are needed and will release an update after we are done checking.
