### ISSUE TITLE
Issues with state

### ISSUE THREAD

**Issue by mcandre** [okta/okta-developer-docs#699]
Some OAuth tutorials recommend using the state parameter to implement dynamic redirects:

https://auth0.com/docs/protocols/oauth2/oauth-state

And the Okta documentation says that the state parameter will be returned in tokens:

https://developer.okta.com/docs/reference/api/oidc/#authorize

However, in practice no such state parameter appears in my tokens. It is silently dropped.

What API request settings / Okta server settings should I use in order to have browser bookmarks redirect to the right places upon successful authentication?

**Comment by jakubvul-okta** [comment]
Hi @mcandre, thanks for your question. Please send your question to support@okta.com, and they should be able to help you.
