### ISSUE TITLE
Reformat all tables

### ISSUE THREAD

**Issue by bretterer** [okta/okta-developer-docs#71]
After migration, there are a bunch of poorly formatted tables in code.  Most of them still render, but someone should go through and re-format all tables in the markdown files to make them look standardized.

<img width="994" alt="Screen Shot 2019-03-22 at 2 14 35 PM" src="https://user-images.githubusercontent.com/1906920/54844274-dc8fac80-4cac-11e9-9fba-2688555670a0.png">

To help with this, you can use the intelliJ plugin https://plugins.jetbrains.com/plugin/7550-pipe-table-formatter

**Comment by nbarbettini** [comment]
For those using VS Code, there are good extensions that will prettify markdown tables. I use this one: https://marketplace.visualstudio.com/items?itemName=yzhang.markdown-all-in-one
