### ISSUE TITLE
Dev Docs: Event Catalog search is broken

### ISSUE THREAD

**Issue by jessstarr-okta** [okta/okta-developer-docs#78]
Search on our public event catalog is broken (https://developer.okta.com/docs/api/resources/event-types/#catalog)

This prevents our users from being able to search through our ~600 events to browse and ID events they need for troubleshooting and/or gaining general knowledge about our events. 

Might be related to the migration to VuePress

cc: @bobtiernay-okta @bretterer

**Comment by bretterer** [comment]
Resolved with #97
