### ISSUE TITLE
Authentication Api, Device context

### ISSUE THREAD

**Issue by andrewvanbeek-okta** [okta/okta-developer-docs#782]
Hi All, looks like the authentication API documentation is slightly off here: https://github.com/okta/okta-developer-docs/blob/master/packages/%40okta/vuepress-site/docs/reference/api/authn/index.md. For Device Token, and Device Context it says it requires API tokens but Postman and curls calls work without it.

**Comment by jakubvul-okta** [comment]
@andrewvanbeek-okta we don't monitor these GH issues. Could you create a Jira using this as your template? https://oktainc.atlassian.net/browse/OKTA-250417

**Comment by eberttc** [comment]
Hi all, when will we have above documentation updated? Because currently is a bit confusing

**Comment by dogeared** [comment]
Track at internal link: https://oktainc.atlassian.net/browse/OKTA-360188
