### ISSUE TITLE
404s

### ISSUE THREAD

**Issue by hamzaessaoui-okta** [okta/okta-developer-docs#85]
I'm not sure if these are related to the migration but here are the 404s from last week

Page | Pageviews
-- | --
developer.okta.com/3rd_party_notices/iOS_Verify.html | 555
developer.okta.com/3rd_party_notices/Android_Verify.html | 297
developer.okta.com/3rd_party_notices/Android_Mobile.html | 147
developer.okta.com/docs/getting_started/okta_expression_lang.html | 96
developer.okta.com/docs/api/resources/users.html | 53
developer.okta.com/docs/api/resources/authn.html | 52
developer.okta.com/docs/api/resources/oidc.html | 45
developer.okta.com/standards/OAuth/ | 41
developer.okta.com/docs/api/resources/oauth2.html | 38
developer.okta.com/docs/api/postman/example.oktapreview.com.environment | 37
developer.okta.com/docs/guides/saml_guidance | 32
developer.okta.com/standards/OIDC/ | 26
developer.okta.com/docs/api/getting_started/design_principles.html | 24
developer.okta.com/standards/SAML/index | 21
developer.okta.com/assets/favicon/index.html | 20
developer.okta.com/docs/api/resources/sessions.html | 15
developer.okta.com/docs/guides/okta_mobile_connect | 15
developer.okta.com/reference/okta_expression_language/index | 14
developer.okta.com/docs/api/getting_started/design_principles/getting_a_token | 13
developer.okta.com/docs/api/getting_started/enabling_cors.html | 10
developer.okta.com/docs/api/getting_started/okta_expression_lang.html | 10

**Comment by bretterer** [comment]
Thank you!  I will get on this right away

**Comment by bretterer** [comment]
Looks like some of these are not 404ing.... where is this list from?

**Comment by hamzaessaoui-okta** [comment]
I get a weekly list of 404s from Google Analytics. These are from last week. Thanks
