### ISSUE TITLE
[Prose]: Breadcrumb bar style unfinished

### ISSUE THREAD

**Issue by bretterer** [okta/okta-developer-docs#907]

**Comment by bretterer** [comment]
@alexdahl-okta What seems to be unfinished about it?

**Comment by alexdahl-okta** [comment]
Looks like a bunch of things here and there:

- Link typography
- Spacing between link items
- Chevron icon color
- Bottom border width
- Bar height

<img width="375" alt="mobile-example" src="https://user-images.githubusercontent.com/26014482/73307346-1f21ef80-41c2-11ea-9cf8-0a857ba545cf.png">

**Comment by bretterer** [comment]
Updated 

<img width="524" alt="Screen Shot 2020-01-30 at 4 05 42 PM" src="https://user-images.githubusercontent.com/1906920/73490375-618e2c80-437a-11ea-949d-b11e7f010ba3.png">
