### ISSUE TITLE
[Prose]: NodeJS quickstart link leads to missing content

### ISSUE THREAD

**Issue by swiftone** [okta/okta-developer-docs#908]
In prod, the link on https://developer.okta.com/code/nodejs/ to the quickstart takes you to:

https://developer.okta.com/quickstart/#/okta-sign-in-page/nodejs/
which immediately bounces you to
https://developer.okta.com/quickstart/#/okta-sign-in-page/nodejs/express

In staging, the quickstart link on 
https://vuepress-site.trexcloud.com/code/nodejs/ 
takes you to
https://vuepress-site.trexcloud.com/quickstart/#/okta-sign-in-page/nodejs/
Which has no content: 
![Screen Shot 2020-01-28 at 1 32 00 PM](https://user-images.githubusercontent.com/492300/73308295-cf005880-41d4-11ea-9485-6ff041664f80.png)

**Comment by bretterer** [comment]
Yes, Thank you!  Quickstarts are not currently working, and will be addressed tomorrow (1/29)

**Comment by bretterer** [comment]
Resolved by #915
