### ISSUE TITLE
Add support for "Edit" links 

### ISSUE THREAD

**Issue by bdemers** [okta/okta-developer-docs#91]
The previous site had "Edit" links that would send the user to GitHub to edit a file and open a Pull Request

**Comment by bretterer** [comment]
https://v1.vuepress.vuejs.org/theme/default-theme-config.html#git-repo-and-edit-links

**Comment by nbarbettini** [comment]
I tried adding that config, but the page template is also missing some stuff that the default template contains to render the edit link. @bretterer Can you put this on your list?
