### ISSUE TITLE
Unformatted content & text overflow onto right side bar

### ISSUE THREAD

**Issue by robertjd** [okta/okta-developer-docs#911]
https://vuepress-site.trexcloud.com/docs/reference/api/groups/

![image](https://user-images.githubusercontent.com/132343/73316058-bbf68400-41e6-11ea-9348-be8201c436f2.png)

**Comment by bretterer** [comment]
Fixed in latest css update on staging https://github.com/okta/okta-developer-docs/commit/e89f7c9686d42c8859101b740bf9c6dd5bd29900

**Comment by bretterer** [comment]
<img width="1036" alt="Screen Shot 2020-02-04 at 2 51 37 PM" src="https://user-images.githubusercontent.com/1906920/73781216-dcca5680-475d-11ea-8464-51d87e88ca73.png">
