### ISSUE TITLE
Show/Hide Contents appears even when useless

### ISSUE THREAD

**Issue by jakubvul-okta** [okta/okta-developer-docs#917]
If you go to a Guide page, or a landing page, and view it at a size that would normally collapse the left nav bar, you will still see the Show/Hide contents link at the top even when there (1) is no collapsed left nav ([Guides](https://vuepress-site.trexcloud.com/docs/guides/sign-into-web-app/aspnet/before-you-begin/)), or no left nav at all ([Landing page](https://vuepress-site.trexcloud.com/docs/reference/)).

**Comment by bretterer** [comment]
Resolved in https://github.com/okta/okta-developer-docs/commit/c44f288564c4c55d309e38428b836f8fc667e01d
