### ISSUE TITLE
[Prose]: Content nav style when inline in body

### ISSUE THREAD

**Issue by alexdahl-okta** [okta/okta-developer-docs#919]
Doesn't have to match mocks exactly; mocks are directional.

- When first loading a page, the first item should appear selected.
- When the list is open, we should indicate headings versus subheadings (H2s versus H3s) somehow. Indentation of subheadings preferred; could also preprend `–` or spaces or somesuch.
- The `On This Page` title should be the same font size as when in a sidebar on larger viewports (1rem).
- The chevron icon should not be cut off on one side.
- If the open dropdown list scrolls horizontally, selected highlights and item dividers should extend the entire width. (Horizontal scrolling doesn't seem great, but I'm not sure if alternatives would be better.)
- When an item has been selected, the input should not have large bottom padding.
- The height of the input should probably not change depending on the item selected, or whether the dropdown is open. Perhaps truncate overflow of the input with an ellipsis `…`?

**Mocks:**

<img width="421" alt="dropdown" src="https://user-images.githubusercontent.com/26014482/73397367-79d14f00-4287-11ea-8370-4109b6147dd9.png">
<img width="375" alt="mobile-example" src="https://user-images.githubusercontent.com/26014482/73397358-75a53180-4287-11ea-8a21-5f8fcd0c5973.png">

**Staging currently:**

<img width="375" alt="staging" src="https://user-images.githubusercontent.com/26014482/73397385-835ab700-4287-11ea-97db-c882ba72d681.png">
<img width="337" alt="Screen Shot 2020-01-29 at 11 11 20 AM" src="https://user-images.githubusercontent.com/26014482/73397807-5f4ba580-4288-11ea-8e1c-d9097814b24f.png">
<img width="360" alt="Screen Shot 2020-01-29 at 11 11 12 AM" src="https://user-images.githubusercontent.com/26014482/73397815-62469600-4288-11ea-9a1b-4161170305cd.png">

**Comment by albertchen-okta** [comment]
tracking in https://oktainc.atlassian.net/browse/OKTA-320804
