### ISSUE TITLE
CRUD operation graphic not rendering correctly

### ISSUE THREAD

**Issue by susanharper-okta** [okta/okta-developer-docs#924]
When defining the CRUD operation graphic, after introducing a variable such as ${applicationId} in the URL and sandwiching in part of the path with another variable, the color is rendering all the way to the end of the URL, coloring items of the URL that shouldn't be colored. For example here:

https://developer.okta.com/docs/reference/api/apps/#get-oauth-2-0-token-for-application

And:
![image (1)](https://user-images.githubusercontent.com/45509385/73581692-4fc68b00-4447-11ea-8e81-1990e4df065d.png)

**Comment by dogeared** [comment]
moved to: https://oktainc.atlassian.net/browse/OKTA-360199
