### ISSUE TITLE
[Prose]: Graphics layout

### ISSUE THREAD

**Issue by IanHakes-okta** [okta/okta-developer-docs#952]
New layout is showing discrepancies for the graphics:

Old style:
<img width="538" alt="Screen Shot 2020-02-14 at 1 44 04 PM" src="https://user-images.githubusercontent.com/54096608/74569887-51f11500-4f30-11ea-9126-7f2cd0fed257.png">

New style:
<img width="571" alt="Screen Shot 2020-02-14 at 1 44 41 PM" src="https://user-images.githubusercontent.com/54096608/74569897-561d3280-4f30-11ea-869a-c1918165bc69.png">

**Comment by bretterer** [comment]
Resolved in 1d4647e7
