### ISSUE TITLE
[Prose]: Narrow breadcrumb issues

### ISSUE THREAD

**Issue by alexdahl-okta** [okta/okta-developer-docs#953]
In narrow viewports, breadcrumb items should not wrap.

Wrapping should not be necessary at iPhone 8 and higher sizes (375px wide).
The left and right padding for the breadcrumb bar appears too high and the source of the problem.

Breadcrumb chevrons should all be the same size.

Screenshot:
<img width="375" alt="screenshot" src="https://user-images.githubusercontent.com/26014482/74803054-b210ef80-527f-11ea-9a90-1ad1477949c4.png">

Mockup:
<img width="375" alt="mobile" src="https://user-images.githubusercontent.com/26014482/74803066-bccb8480-527f-11ea-859f-ce4f8501c138.png">

Chrome 80.0.3987.116 on macOS 10.14.6.

Design priority: medium.
See also:
- https://github.com/okta/okta-developer-docs/projects/4#card-31370466
- https://github.com/okta/okta-developer-docs/issues/907

**Comment by bretterer** [comment]
Can not re-produce:

Left to right: Brave, Chrome, Safari, Firefox
<img width="1989" alt="Screen Shot 2020-02-19 at 9 23 49 AM" src="https://user-images.githubusercontent.com/1906920/74843722-53d52280-52fa-11ea-8eab-535770f0b1f4.png">

**Comment by alexdahl-okta** [comment]
@bretterer, you should be able to get narrower viewports on real devices or in Chrome inspector's device mode:
<img width="1439" alt="Screen Shot 2020-02-19 at 10 56 27 AM" src="https://user-images.githubusercontent.com/26014482/74875684-c3e9a580-5306-11ea-8c79-ae4b1d5bdc29.png">

**Comment by bretterer** [comment]
Sure, I made it smaller with that window, but look at the length of the text.   That will never fit on a single line.

**Comment by alexdahl-okta** [comment]
It should! With the extra breadcrumb bar padding removed:
<img width="1552" alt="Screen Shot 2020-02-19 at 5 13 40 PM" src="https://user-images.githubusercontent.com/26014482/74897467-48561b80-533b-11ea-9bc7-97c7625daf8e.png">

**Comment by bretterer** [comment]
Done, #977
