### ISSUE TITLE
[Prose]: Safari mobile nav too tall

### ISSUE THREAD

**Issue by alexdahl-okta** [okta/okta-developer-docs#954]
In narrow viewports in Safari, the top nav should not be excessively tall and cover up other UI.

The addition of search to the top nav when collapsed postdates the design, but is good. Top nav should be consistent with marketing pages.

Screenshot:
<img width="375" alt="screenshot" src="https://user-images.githubusercontent.com/26014482/74803413-d9b48780-5280-11ea-9c07-68f2d97c3f48.jpeg">

Mockup:
<img width="375" alt="mobile" src="https://user-images.githubusercontent.com/26014482/74803428-e638e000-5280-11ea-9414-0ba96fcbe247.png">

Safari 13.0.5 (14608.5.12) on macOS 10.14.6; iOS 13.3.1.

Design priority: high.
See also: https://github.com/okta/okta-developer-docs/projects/4#card-32286504

**Comment by bretterer** [comment]
Resolved via #962
