### ISSUE TITLE
[Prose]: Safari reference icon spacing

### ISSUE THREAD

**Issue by alexdahl-okta** [okta/okta-developer-docs#955]
In Safari, the icons for list items on https://vuepress-site.trexcloud.com/docs/reference/ are spaced incorrectly. They should match the spacing on prod: https://developer.okta.com/docs/reference/.

Alternatively, we could go directly to a new Reference Overview page with the prose layout, which eliminates these icons: https://oktainc.atlassian.net/browse/OKTA-265887

As this is the second instance of SVG spacing issues we've seen in Safari, we should probably audit all appearances of SVGs across the site and/or implement a global solution.

Screenshot:
<img width="1440" alt="Screen Shot 2020-02-18 at 7 05 12 PM" src="https://user-images.githubusercontent.com/26014482/74803671-e4235100-5281-11ea-82da-b3a098db4de8.png">

Desired:
<img width="1440" alt="Screen Shot 2020-02-18 at 7 07 04 PM" src="https://user-images.githubusercontent.com/26014482/74803678-eab1c880-5281-11ea-9843-03d2f476c29b.png">

Safari 13.0.5 (14608.5.12) on macOS 10.14.6.

Design priority: high.

**Comment by bretterer** [comment]
Resolved by #963
