### ISSUE TITLE
[Prose]: Languages & SDKs overview page cards on mobile

### ISSUE THREAD

**Issue by alexdahl-okta** [okta/okta-developer-docs#956]
If we use this content, cards on the Languages & SDKs overview page (https://vuepress-site.trexcloud.com/code/) should be responsive. The page should not scroll horizontally, card icons should not overflow their cards, and card icons should probably be smaller overall.

Alternatively, we could replace the page content. The card content is outdated and not desired. Section overview pages should introduce the section, help users understand what parts of the section might be relevant to them, provide relevant information for search engines, and feature any content that is especially important or helpful for new users. Section overview pages should not be an index that is redundant with tree nav.

Screenshot:
![code-mobile](https://user-images.githubusercontent.com/26014482/74803961-dde1a480-5282-11ea-8aa4-58e262852144.png)

Chrome 80.0.3987.116 on macOS 10.14.6.

Design priority: medium.

**Comment by bretterer** [comment]
Resolved by #964

**Comment by alexdahl-okta** [comment]
Unresolved. Looks like a fix was prepared, but never merged to master.

**Comment by alexdahl-okta** [comment]
Tracking as https://oktainc.atlassian.net/browse/OKTA-332531
