### ISSUE TITLE
[Prose]: Tree nav width and arrows

### ISSUE THREAD

**Issue by alexdahl-okta** [okta/okta-developer-docs#960]
- In wider viewports, the tree nav and content nav should be a fixed width – design estimate is `18rem`.
- When expanding and collapsing tree nav sub-sections, the width of the tree nav and line wrapping of tree nav items should not change.
- When navigating between pages, the width of the tree nav and line wrapping of tree nav items should not change.
- All sub-section disclosure triangles in the tree nav should be the same size.
- Sub-section disclosure triangles should be aligned with the first line of their item, like active indicators in tree nav and content nav.
- Clicking on a disclosure triangle should expand or collapse the item.

Screenshot:
<img width="1174" alt="Screen Shot 2020-02-18 at 7 40 20 PM" src="https://user-images.githubusercontent.com/26014482/74805429-2307d580-5287-11ea-9087-821d9ee317fb.png">

Mockup:
<img width="1100" alt="medium" src="https://user-images.githubusercontent.com/26014482/74805503-56e2fb00-5287-11ea-8b80-0fa6a1438d9e.png">

Chrome 80.0.3987.116 on macOS 10.14.6.

Design priority: medium.
See also:
- https://github.com/okta/okta-developer-docs/projects/4#card-31376434
- https://github.com/okta/okta-developer-docs/issues/951

**Comment by albertchen-okta** [comment]
closing this, we're tracking in https://oktainc.atlassian.net/browse/OKTA-327765
