### ISSUE TITLE
[Prose]: Content nav rail width

### ISSUE THREAD

**Issue by alexdahl-okta** [okta/okta-developer-docs#961]
In wide viewports with content nav in a trailing sidebar, its rail and active indicator should be wider. The active indicator should be positioned on top of the rail.

The width should match the active indicator in tree nav (`3px`).

Screenshot:
<img width="287" alt="Screen Shot 2020-02-18 at 7 52 39 PM" src="https://user-images.githubusercontent.com/26014482/74805777-3ff0d880-5288-11ea-8701-46d7c4213e92.png">

Mockup:
<img width="257" alt="mockup" src="https://user-images.githubusercontent.com/26014482/74805801-55660280-5288-11ea-9916-437cb511c200.png">

Chrome 80.0.3987.116 on macOS 10.14.6.

Design priority: low.
See also:
- https://github.com/okta/okta-developer-docs/projects/4#card-32287390
- https://github.com/okta/okta-developer-docs/projects/4#card-31377403

**Comment by bretterer** [comment]
Resolved by #965

**Comment by alexdahl-okta** [comment]
Looks like a fix was prepared, but never merged to master.

**Comment by albertchen-okta** [comment]
Tracking in https://oktainc.atlassian.net/browse/OKTA-320821
