### ISSUE TITLE
[Prose]: Overview and ancestor active states in tree nav

### ISSUE THREAD

**Issue by alexdahl-okta** [okta/okta-developer-docs#966]
When viewing articles in a section, the tree nav link to the section overview page should not be bold. It should have the same state as other non-active articles in the section.

When viewing an article with ancestors in the hierarchy, the ancestors should have a bold active state.
For example, for `Guides` > `Sign Users In` > `Mobile App` > `Unlock a mobile app with biometrics` > `Overview`:
`Sign Users In` > `Mobile App` > `Unlock a mobile app with biometrics` should all be bold, because they are the ancestors of the article.

The guides _overview article_ should not be active, because it is not an ancestor. The guides _section_ is an ancestor, but it does not appear in the tree nav.

Screenshots:
<img width="482" alt="Screen Shot 2020-02-19 at 10 54 50 AM" src="https://user-images.githubusercontent.com/26014482/74876405-b41e9100-5307-11ea-89de-581fbc09ada6.png">
<img width="575" alt="Screen Shot 2020-07-23 at 1 04 44 PM" src="https://user-images.githubusercontent.com/26014482/88346865-1d566600-cce5-11ea-8ee2-ae3c4bfa736a.png">

Mockup:
<img width="231" alt="Screen Shot 2020-07-23 at 1 06 12 PM" src="https://user-images.githubusercontent.com/26014482/88346953-4f67c800-cce5-11ea-9012-8066e5b3899c.png">

Chrome 84.0.4147.89 on macOS 10.15.5.

Design priority: low.

**Comment by alexdahl-okta** [comment]
With a link to the Languages & SDKs overview page added to the tree nav in that section – #980 – looks like this is a more general issue. The section overview page has a special state in multiple sections.

(It should not, it should have the same state as other non-active articles in the section.)

**Comment by albertchen-okta** [comment]
Tracking in https://oktainc.atlassian.net/browse/OKTA-320822
