### ISSUE TITLE
[Prose]: Tree nav needs additional levels in Languages & SDKs

### ISSUE THREAD

**Issue by alexdahl-okta** [okta/okta-developer-docs#968]
Some languages pages, such as JavaScript, have children underneath them. When viewing a child article, the Tree Nav should not incorrectly indicate that the language page is active.

The tree nav should support arbitrary depth and show JavaScript as a sub-section with child articles.

Screenshot:
<img width="724" alt="Screen Shot 2020-02-19 at 11 32 30 AM" src="https://user-images.githubusercontent.com/26014482/74878737-ed590000-530b-11ea-98e0-b59a899b8b03.png">

Chrome 80.0.3987.116 on macOS 10.14.6.

Design priority: medium.
See also: 
- https://github.com/okta/okta-developer-docs/projects/4#card-32287204
- https://github.com/okta/okta-developer-docs/projects/4#card-31378727

**Comment by albertchen-okta** [comment]
tracking in https://oktainc.atlassian.net/browse/OKTA-320797
