### ISSUE TITLE
[Prose]: Content nav width

### ISSUE THREAD

**Issue by alexdahl-okta** [okta/okta-developer-docs#970]
In larger viewports, when the content nav appears in a trailing sidebar, the content nav should have a fixed width. It should not cut off its contents or cause the page to scroll horizontally.

Content nav and tree nav should have the same width in large viewports.

For example: https://vuepress-site.trexcloud.com/docs/reference/okta-expression-language/

Screenshot:
<img width="999" alt="Screen Shot 2020-02-19 at 11 48 51 AM" src="https://user-images.githubusercontent.com/26014482/74879867-272b0600-530e-11ea-95e9-eadd251fa79b.png">

Chrome 80.0.3987.116 on macOS 10.14.6.

Design priority: high.
See also:
- https://github.com/okta/okta-developer-docs/issues/960
- https://github.com/okta/okta-developer-docs/projects/4#card-31376434

**Comment by albertchen-okta** [comment]
Closing, tracking in JIRA: https://oktainc.atlassian.net/browse/OKTA-331496
