### ISSUE TITLE
[Prose]: Guides button typography

### ISSUE THREAD

**Issue by alexdahl-okta** [okta/okta-developer-docs#973]
Buttons in guides should match button appearance across the site.
Button labels should be uppercase and not underlined. Buttons that open in a new tab should be marked with an icon.

For example: https://developer.okta.com/docs/guides/sign-into-web-app/aspnet/create-okta-application/

Even if refactoring guides is out of scope, we should not introduce regressions.

Screenshot:
<img width="836" alt="Screen Shot 2020-02-19 at 1 14 02 PM" src="https://user-images.githubusercontent.com/26014482/74885609-17b1ba00-531a-11ea-9f9f-f935584eefe5.png">

Desired:
<img width="979" alt="Screen Shot 2020-02-19 at 1 16 34 PM" src="https://user-images.githubusercontent.com/26014482/74885621-1ed8c800-531a-11ea-9d55-954deead1eae.png">

Chrome 80.0.3987.116 on macOS 10.14.6.

Design priority: low.

**Comment by dogeared** [comment]
moved to: https://oktainc.atlassian.net/browse/OKTA-360202
