### ISSUE TITLE
[Prose]: Release notes layout

### ISSUE THREAD

**Issue by alexdahl-okta** [okta/okta-developer-docs#975]
The release notes page should not include broken navigation components.

If the release notes layout does include functional tree nav and content nav, they should not appear at all. A tree nav border and content nav "On This Page" title should not appear.

Screenshot:
<img width="1048" alt="Screen Shot 2020-02-19 at 1 24 42 PM" src="https://user-images.githubusercontent.com/26014482/74886190-90fddc80-531b-11ea-8c27-d5b657a4d75b.png">

Chrome 80.0.3987.116 on macOS 10.14.6.

Design priority: medium.

**Comment by alexdahl-okta** [comment]
The  "On This Page" title appears to have been resolved, but the tree nav border still appears.

**Comment by dogeared** [comment]
moved to: https://oktainc.atlassian.net/browse/OKTA-360203
