### ISSUE TITLE
[Prose]: Narrow search padding

### ISSUE THREAD

**Issue by alexdahl-okta** [okta/okta-developer-docs#976]
In narrow viewports, when the search in the top nav is open, the search bar should have left and right padding.

Top nav search should match marketing pages.

Screenshot:
![vuepress-site trexcloud com_code_react_(iPhone 6_7_8)](https://user-images.githubusercontent.com/26014482/74897888-75ef9480-533c-11ea-83a1-e63ed9e9d361.png)

Desired:
![developer okta com_docs_reference_(iPhone 6_7_8)](https://user-images.githubusercontent.com/26014482/74897898-7a1bb200-533c-11ea-9a0c-8a3068bc0302.png)

Chrome 80.0.3987.116 on macOS 10.14.6.

Design priority: low.

**Comment by dogeared** [comment]
moved to: https://oktainc.atlassian.net/browse/OKTA-360206
