### ISSUE TITLE
[Prose]: Tree nav and content nav colors

### ISSUE THREAD

**Issue by alexdahl-okta** [okta/okta-developer-docs#979]
Followup from #965.

The content nav rail is too dark. It should be Gray 100, `#E4E5E7`.
The tree nav border is too dark. It should be `$border-default` or `$base-border-color`, Gray 300, `#B7BCC0`.

Screenshot:
<img width="1440" alt="annotated" src="https://user-images.githubusercontent.com/26014482/74900421-d2a27d80-5343-11ea-8faa-31f655caff03.png">

Mockup:
<img width="1440" alt="Large" src="https://user-images.githubusercontent.com/26014482/74900426-d7673180-5343-11ea-825a-a6e13a6d1cdd.png">

Chrome 80.0.3987.116 on macOS 10.14.6.

Design priority: low.

**Comment by albertchen-okta** [comment]
Tracking in https://oktainc.atlassian.net/browse/OKTA-320823
