### ISSUE TITLE
Missing ASP.NET Core icon in guides

### ISSUE THREAD

**Issue by laura-rodriguez** [okta/okta-developer-docs#983]
![image](https://user-images.githubusercontent.com/16751130/74948643-98c88a00-53ca-11ea-9ec0-e119ed0877bc.png)

I'll fix this today.

**Comment by alexdahl-okta** [comment]
👏

Doesn't necessarily have to be in scope for this issue, but looks like we've added at least a couple more stack options without human-readable text. In addition to `ASPNETCORE3`, I've also seen `AZURE`. All stack options should have a string defined for humans.

**Comment by laura-rodriguez** [comment]
This should be fixed by #995 . There were several missing values, `Azure` among them.
