### ISSUE TITLE
Nav logo is missing the homepage link

### ISSUE THREAD

**Issue by hamzaessaoui-okta** [okta/okta-developer-docs#985]
The link should be https://developer.okta.com/ 

<img width="315" alt="Screen Shot 2020-02-20 at 8 01 59 AM" src="https://user-images.githubusercontent.com/47118245/74954122-7b3df500-53b7-11ea-8ae3-acdebc11ea0a.png">

**Comment by bretterer** [comment]
This is already resolved by #984
