### ISSUE TITLE
[Prose]: Graphics do not have linebreaks after descriptions

### ISSUE THREAD

**Issue by IanHakes-okta** [okta/okta-developer-docs#989]
Weird graphics behaviour that wasn't present before the Prose update. Graphics are on the same line as the descriptor text, instead of on new lines, so the pages are all screwy-looking. (That is my technical term).
<img width="509" alt="Screen Shot 2020-02-20 at 1 37 11 PM" src="https://user-images.githubusercontent.com/54096608/74969361-75153c00-53ea-11ea-86ee-d58715fe3ce7.png">

**Comment by bretterer** [comment]
What URL are you seeing this on @IanHakes-okta.  What browser are you using?

**Comment by IanHakes-okta** [comment]
https://developer.okta.com/docs/guides/build-provisioning-integration/prepare-app/ is the one I stumbled across. Haven't had time to test out other locations with graphics.

Chrome Version 80.0.3987.106 (Official Build) (64-bit)

**Comment by jakubvul-okta** [comment]
Also on our Release Notes page, in Chromium: https://developer.okta.com/docs/release-notes/

<img width="856" alt="Screen Shot 2020-02-20 at 5 37 13 PM" src="https://user-images.githubusercontent.com/26014374/74986834-e3b4c280-5407-11ea-9236-8e4f96ea77e4.png">

**Comment by alexdahl-okta** [comment]
A global `img { display: block; }` would probably fix this, but might cause other issues. I'm not sure if all images were `block` before.

**Comment by alexdahl-okta** [comment]
This appears resolved on some pages, but not others. For example, https://developer.okta.com/docs/guides/build-provisioning-integration/attribute-mapping/

<img width="699" alt="Screen Shot 2020-05-28 at 2 54 11 PM" src="https://user-images.githubusercontent.com/26014482/83209098-223ad700-a0f3-11ea-9be3-3e3cf5afd947.png">

So I'm guessing this is still unresolved.

**Comment by dogeared** [comment]
moved to: https://oktainc.atlassian.net/browse/OKTA-360207
