### ISSUE TITLE
[Prose]: Guide nav shows underlining for all

### ISSUE THREAD

**Issue by IanHakes-okta** [okta/okta-developer-docs#991]
Issue: All of the items in the Guide Nav show the hyperlink underlining:

<img width="327" alt="Screen Shot 2020-02-20 at 5 11 39 PM" src="https://user-images.githubusercontent.com/54096608/74984872-65a2ec80-5404-11ea-8919-279e99c7032c.png">

Previous style:
<img width="299" alt="Screen Shot 2020-02-20 at 5 11 46 PM" src="https://user-images.githubusercontent.com/54096608/74984898-73587200-5404-11ea-9190-922a9251509e.png">

URL: https://developer.okta.com/docs/guides/build-provisioning-integration/prepare-app/ (well, everywhere in the Guides subdirectory shows it)
Chrome V80

**Comment by alexdahl-okta** [comment]
Resolved!
