### ISSUE TITLE
[Prose]: Global button styles

### ISSUE THREAD

**Issue by alexdahl-okta** [okta/okta-developer-docs#992]
Followup from #981. Issue #957 identified some issues with buttons on language pages.
Somewhat related, #973 identified issues with buttons in guides.

Button styles should be global and consistent across the site.

Buttons should be responsive and be usable with any length of label, with any number of buttons next to each other, in any viewport size.

Language page CTAs should not need special treatment. They should not need a `ul`, `flex`, or unique style declarations.

**Comment by alexdahl-okta** [comment]
Both #957 and #973 are still open and occurring.

I think it's helpful to leave this issue open as well – other bugs could be fixed with one-off solutions, but this issue is for a global enhancement.

**Comment by dogeared** [comment]
moved to: https://oktainc.atlassian.net/browse/OKTA-360207
