### ISSUE TITLE
[okta_angular_auth_js] Missing argument in code snippet

### ISSUE THREAD

**Issue by shuowu-okta** [okta/okta-developer-docs#996]
Mandatory argument is missing from `app.component.html` snippet in [Add Routes](https://developer.okta.com/code/angular/okta_angular_auth_js/#add-routes) section.

Warning from angular console:
```
ERROR in src/app/app.component.html:2:43 - error TS2554: Expected 1 arguments, but got 0.
    
    2 <button *ngIf="!isAuthenticated" (click)="oktaAuth.login()"> Login </button>
                                                ~~~~~~~~~~~~~~~~
    
      src/app/app.component.ts:6:16
        6   templateUrl: './app.component.html',
                         ~~~~~~~~~~~~~~~~~~~~~~
        Error occurs in the template of component AppComponent.
```

**Comment by kartikcallingkartik** [comment]
Hi can you let me know how did you solve this?
I am also getting the same issue.

**Comment by dogeared** [comment]
Internal tracking link: https://oktainc.atlassian.net/browse/OKTA-360212

**Comment by brianduffield-okta** [comment]
The applicable code on this old guide is updated. I'll run through this guide shortly and hopefully close the issue.
