### ISSUE TITLE
[Prose]: Content nav overflow polish

### ISSUE THREAD

**Issue by alexdahl-okta** [okta/okta-developer-docs#998]
In large viewports, should the bottom of body content have more/dynamic padding, so that the `On This Page` content nav shows more of its items while still reading toward the bottom of the page?

<img width="1555" alt="padding" src="https://user-images.githubusercontent.com/26014482/75075605-4bb7e700-54a2-11ea-8c99-8eca667bffe8.png">

**Comment by dogeared** [comment]
moved to: https://oktainc.atlassian.net/browse/OKTA-360231
